# 변수 모으기

user_id 기반으로 유의미한 feature를 하나씩 모아보겠습니다. 다 합쳐서 써보죠 뭐.

# IMPORT & LOAD DATA

In [1]:
import load_dtypes as ld
import warnings
warnings.filterwarnings(action='ignore')

import os, sys
import time
import datetime as dt

import numpy as np
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 500)

import matplotlib.pyplot as plt
import seaborn as sns

from tqdm import tqdm

from sklearn.model_selection import train_test_split
from sklearn.metrics import auc, roc_auc_score, roc_curve, precision_recall_curve, recall_score, precision_score

import lightgbm as lgb
from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.model_selection import StratifiedKFold

In [2]:
#-------------------------------------------------------------------------------------
# validation auc score를 확인하기 위해 정의
def f_pr_auc(probas_pred, y_true):
    labels=y_true.get_label()
    p, r, _ = precision_recall_curve(labels, probas_pred)
    score=auc(r,p) 
    return "pr_auc", score, True
#-------------------------------------------------------------------------------------

In [3]:
TRAIN_P_PATH = r'C:\Users\Wyatt\wyatt37/Data/systemError/train_problem_data.csv'
TRAIN_Q_PATH = r'C:\Users\Wyatt\wyatt37/Data/systemError/train_quality_data.csv'
TRAIN_E_PATH = r'C:\Users\Wyatt\wyatt37/Data/systemError/train_err_data.csv'
TEST_Q_PATH = r'C:\Users\Wyatt\wyatt37/Data/systemError/test_quality_data.csv'
TEST_E_PATH = r'C:\Users\Wyatt\wyatt37/Data/systemError/test_err_data.csv'
SUBMISSION_PATH = r'C:\Users\Wyatt\wyatt37/Data/systemError/sample_submission.csv'

In [4]:
%%time
train_p = ld.load_dtypes(TRAIN_P_PATH)
train_q = ld.load_dtypes(TRAIN_Q_PATH)
train_e = ld.load_dtypes(TRAIN_E_PATH)
test_q = ld.load_dtypes(TEST_Q_PATH)
test_e = ld.load_dtypes(TEST_E_PATH)
submission = pd.read_csv(SUBMISSION_PATH)

C:\Users\Wyatt\wyatt37/Data/systemError/train_problem_data.csv
C:\Users\Wyatt\wyatt37/Data/systemError/train_quality_data.csv
C:\Users\Wyatt\wyatt37/Data/systemError/train_err_data.csv
C:\Users\Wyatt\wyatt37/Data/systemError/test_quality_data.csv
C:\Users\Wyatt\wyatt37/Data/systemError/test_err_data.csv
Wall time: 1min 17s

In [5]:
train_p.shape, train_q.shape, train_e.shape, test_q.shape, test_e.shape, submission.shape

((5429, 2),
 (828624, 16),
 (16554663, 6),
 (747972, 16),
 (16532648, 6),
 (14999, 2))

In [6]:
def preprocessing_problem(df, object_='binary'):
    """
    definition:
    train_problem 테이블을 받아서 target 값으로 변환
    1. {0, 1}의 binary로 변환
    2. {0 ~ n}의 multiclass로 변환
    """
    
    # 10001부터 24999까지의 index를 만들어줍니다.
    user_id_idx = np.array(range(10000, 25000, 1))
    
    # train_new_p라는 새로운 df를 만들고 index는 위에서 만든 user_id_idx 로 지정해줍니다.
    new_p = pd.DataFrame(index = user_id_idx)
    new_p['target'] = 0
    
    if object_ == 'binary':
        new_p.iloc[df.user_id.unique()-10000] = 1
        new_p = new_p.reset_index()
        new_p.rename({'index':'user_id'}, axis=1, inplace=True)
        
    elif object_ == 'multi':
        # multi는 count()로 집계를 해줍니다.
        new_p['target'] = df.groupby('user_id')['time'].count()
        new_p = new_p.fillna(0)
        new_p = new_p.reset_index()
        new_p.rename({'index':'user_id'}, axis=1, inplace=True)
        
    return new_p

In [7]:
train_b_p = preprocessing_problem(train_p, 'binary')
train_m_p = preprocessing_problem(train_p, 'multi')

In [8]:
def preprocessing_quality(df):
    """
    definition:
    EDA를 통해 알아낸 정보로 train_q, test_q를 정리해서 내뿜어줍니다.
    1. qaulity_3, quality_4 를 drop 합니다.(단일 value)
    2. qaulity_k 변수들을 정수로 encoding 합니다.
    """
    # 먼저 3, 4번을 drop 합니다.
    df.drop(['quality_3', 'quality_4'], axis=1, inplace=True)
    
    # qual 변수만 할당해주고, 정수로 형변환 해줍니다.
    columns = train_q.columns[train_q.columns.str.contains('quality')]
    # for문을 통해 각 column을 반복 작업해줍니다.
    for col in columns:
        try:
            if df[col].dtype == 'float32': # 기존에 float은 패스
                df[col] = df[col].fillna(-2)
            elif df[col].dtype == 'int8' or df[col].dtype == 'int16': # 기존에 int도 패스
                df[col] = df[col].fillna(-2)
                #print(col)
            else:
                df[col] = df[col].astype('object')
                # nan값이 있으면 float으로 갈 수 없으니 '-2' 으로 채워줍니다.
                df[col] = df[col].fillna('-2')
                df[col] = df[col].apply(lambda x: x.replace(',' , ''))
                df[col] = df[col].astype(np.float32)
        except:
            pass
        
    # fwver 에서 null 값이 꽤 있습니다. missing으로 채우겠습니다.
    df.fwver = df.fwver.astype('object')
    df.fwver = df.fwver.fillna('missing')
    df.fwver = df.fwver.astype('category')
        
    return df

In [9]:
train_q = preprocessing_quality(train_q)
test_q = preprocessing_quality(test_q)

In [10]:
def preprocessing_fwver(df):
    """
    definition:
    별건 아니고, e-set에 fwver 변수에서 '10' 이라는 값이 있는데, 이게 errtype이랑 겹쳐요.
    그래서 10을 -> 8.5.2 으로 바꿔줄 겁니다.
    굳이 이렇게 바꾸는 이유는, 해당 fw가 8.5.3버전과 같은 model_nm을 공유하기 때문입니다.
    """
    df.fwver = df.fwver.replace('10', '8.5.2')
        
    return df

In [11]:
train_e = preprocessing_fwver(train_e)
test_e = preprocessing_fwver(test_e)

In [12]:
def make_datetime(df, column_name):
    # df 와 column_name을 받아서 datetime 컬럼을 반환해주는 함수
    
    df['year'] = df[column_name].apply(lambda x: str(x)[:4])
    df['month'] = df[column_name].apply(lambda x: str(x)[4:6])
    df['day'] = df[column_name].apply(lambda x: str(x)[6:8])
    df['hour'] = df[column_name].apply(lambda x: str(x)[8:10])
    df['minute'] = '00' # minute을 넣어주지 않으면 datetime이 완성이 안되니, 00으로 넣어줍니다.
    
    df[column_name] = pd.to_datetime(df.year + df.month + df.day + df.hour + df.minute)
    
    return df

In [13]:
train_p = make_datetime(train_p, 'time')
train_q = make_datetime(train_q, 'time')
test_q = make_datetime(test_q, 'time')
train_e = make_datetime(train_e, 'time')
test_e = make_datetime(test_e, 'time')

# Feature Collection

## err_count based on user_id by train_e

유저 당 err가 몇 번이나 떴는가에 대한 단순 집계입니다. 시리즈로 뽑겠습니다.

In [15]:
train_err_count = train_e.groupby('user_id')['errcode'].count()
test_err_count = test_e.groupby('user_id')['errcode'].count()

In [16]:
train_err_count

user_id
10000     317
10001    2365
10002     306
10003     306
10004     777
         ...
24995     194
24996       4
24997     826
24998     155
24999     570
Name: errcode, Length: 15000, dtype: int64

In [17]:
test_err_count

user_id
30000     2750
30001      284
30002      941
30003      371
30004      881
         ...
44994     1115
44995      515
44996     2233
44997    24671
44998      873
Name: errcode, Length: 14998, dtype: int64

## ddddddddddddd

In [22]:
train_e.groupby(['user_id', 'model_nm']).count().reset_index().dropna()

,user_id,model_nm,time,fwver,errtype,errcode,year,month,day,hour,minute
3,10000,model_3,317.0,317.0,317.0,317.0,317.0,317.0,317.0,317.0,317.0
11,10001,model_2,2365.0,2365.0,2365.0,2365.0,2365.0,2365.0,2365.0,2365.0,2365.0
21,10002,model_3,306.0,306.0,306.0,306.0,306.0,306.0,306.0,306.0,306.0
29,10003,model_2,306.0,306.0,306.0,306.0,306.0,306.0,306.0,306.0,306.0
36,10004,model_0,777.0,777.0,777.0,777.0,777.0,777.0,777.0,777.0,777.0
...,...,...,...,...,...,...,...,...,...,...,...
134957,24995,model_2,194.0,194.0,194.0,194.0,194.0,194.0,194.0,194.0,194.0
134967,24996,model_3,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0
134973,24997,model_0,826.0,826.0,826.0,826.0,826.0,826.0,826.0,826.0,826.0
134982,24998,model_0,155.0,155.0,155.0,155.0,155.0,155.0,155.0,155.0,155.0
134994,24999,model_3,570.0,570.0,570.0,570.0,570.0,570.0,570.0,570.0,570.0

In [29]:
train_e.groupby(['fwver', 'model_nm']).count().dropna().reset_index()

,fwver,model_nm,user_id,time,errtype,errcode,year,month,day,hour,minute
0,03.11.1149,model_4,2114.0,2114.0,2114.0,2114.0,2114.0,2114.0,2114.0,2114.0,2114.0
1,03.11.1167,model_4,1505659.0,1505659.0,1505659.0,1505659.0,1505659.0,1505659.0,1505659.0,1505659.0,1505659.0
2,04.16.3553,model_1,5237816.0,5237816.0,5237816.0,5237816.0,5237816.0,5237816.0,5237816.0,5237816.0,5237816.0
3,04.16.3571,model_1,145156.0,145156.0,145156.0,145156.0,145156.0,145156.0,145156.0,145156.0,145156.0
4,04.22.1684,model_0,5554.0,5554.0,5554.0,5554.0,5554.0,5554.0,5554.0,5554.0,5554.0
5,04.22.1750,model_0,2874213.0,2874213.0,2874213.0,2874213.0,2874213.0,2874213.0,2874213.0,2874213.0,2874213.0
6,04.22.1778,model_0,1293946.0,1293946.0,1293946.0,1293946.0,1293946.0,1293946.0,1293946.0,1293946.0,1293946.0
7,04.33.1149,model_2,3272.0,3272.0,3272.0,3272.0,3272.0,3272.0,3272.0,3272.0,3272.0
8,04.33.1171,model_2,58.0,58.0,58.0,58.0,58.0,58.0,58.0,58.0,58.0
9,04.33.1185,model_2,963736.0,963736.0,963736.0,963736.0,963736.0,963736.0,963736.0,963736.0,963736.0
10,04.33.1261,model_2,2504871.0,2504871.0,2504871.0,2504870.0,2504871.0,2504871.0,2504871.0,2504871.0,2504871.0
11,04.82.1684,model_5,23554.0,23554.0,23554.0,23554.0,23554.0,23554.0,23554.0,23554.0,23554.0
12,04.82.1778,model_5,8601.0,8601.0,8601.0,8601.0,8601.0,8601.0,8601.0,8601.0,8601.0
13,05.15.2138,model_3,1906479.0,1906479.0,1906479.0,1906479.0,1906479.0,1906479.0,1906479.0,1906479.0,1906479.0
14,05.66.3237,model_7,31832.0,31832.0,31832.0,31832.0,31832.0,31832.0,31832.0,31832.0,31832.0
15,05.66.3571,model_7,3524.0,3524.0,3524.0,3524.0,3524.0,3524.0,3524.0,3524.0,3524.0
16,04.73.2237,model_8,33537.0,33537.0,33537.0,33537.0,33537.0,33537.0,33537.0,33537.0,33537.0
17,10.10.1000,model_6,1534.0,1534.0,1534.0,1534.0,1534.0,1534.0,1534.0,1534.0,1534.0
18,04.82.1730,model_5,78.0,78.0,78.0,78.0,78.0,78.0,78.0,78.0,78.0
19,04.73.2571,model_8,2527.0,2527.0,2527.0,2527.0,2527.0,2527.0,2527.0,2527.0,2527.0
20,8.5.3,model_6,212.0,212.0,212.0,212.0,212.0,212.0,212.0,212.0,212.0
21,04.22.1666,model_0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0
22,03.11.1141,model_4,29.0,29.0,29.0,29.0,29.0,29.0,29.0,29.0,29.0
23,05.15.2120,model_3,706.0,706.0,706.0,706.0,706.0,706.0,706.0,706.0,706.0
24,04.33.1125,model_2,408.0,408.0,408.0,408.0,408.0,408.0,408.0,408.0,408.0
25,04.16.3439,model_1,142.0,142.0,142.0,142.0,142.0,142.0,142.0,142.0,142.0
26,04.22.1442,model_0,2522.0,2522.0,2522.0,2522.0,2522.0,2522.0,2522.0,2522.0,2522.0
27,04.33.1095,model_2,909.0,909.0,909.0,909.0,909.0,909.0,909.0,909.0,909.0
28,04.16.3569,model_1,980.0,980.0,980.0,980.0,980.0,980.0,980.0,980.0,980.0
29,05.15.2090,model_3,12.0,12.0,12.0,12.0,12.0,12.0,12.0,12.0,12.0
30,05.15.3104,model_3,191.0,191.0,191.0,191.0,191.0,191.0,191.0,191.0,191.0
31,05.15.2122,model_3,23.0,23.0,23.0,23.0,23.0,23.0,23.0,23.0,23.0
32,04.22.1656,model_0,39.0,39.0,39.0,39.0,39.0,39.0,39.0,39.0,39.0
33,04.16.2641,model_1,296.0,296.0,296.0,296.0,296.0,296.0,296.0,296.0,296.0
34,05.15.2114,model_3,9.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0
35,04.16.3345,model_1,101.0,101.0,101.0,101.0,101.0,101.0,101.0,101.0,101.0
36,05.15.2092,model_3,18.0,18.0,18.0,18.0,18.0,18.0,18.0,18.0,18.0

In [44]:
test_e.groupby(['fwver', 'model_nm'])['user_id'].sum().dropna().reset_index()

         fwver model_nm       user_id
0   03.11.1167  model_4  4.678189e+10
1   04.16.3553  model_1  1.998926e+11
2   04.16.3571  model_1  5.543469e+09
3   04.22.1684  model_0  1.781200e+08
4   04.22.1750  model_0  1.110284e+11
5   04.22.1778  model_0  5.141634e+10
6   04.33.1149  model_2  1.982947e+08
7   04.33.1185  model_2  3.681017e+10
8   04.33.1261  model_2  9.702149e+10
9   05.15.2120  model_3  1.677693e+07
10  05.15.2138  model_3  6.940451e+10
11  04.82.1684  model_5  8.355523e+08
12  04.82.1778  model_5  4.327014e+08
13  05.66.3237  model_7  9.519245e+08
14  10.10.1000  model_6  2.146142e+07
15  04.73.2237  model_8  7.646015e+08
16  04.73.2569  model_8  5.175990e+05
17  04.73.2571  model_8  1.556966e+08
18  04.73.2577  model_8  1.613691e+06
19  04.82.1730  model_5  9.621417e+06
20  04.22.1478  model_0  1.652789e+07
21       8.5.3  model_6  5.297310e+05
22  04.22.1656  model_0  3.674403e+07
23  04.22.1666  model_0  1.695969e+06
24  03.11.1149  model_4  1.933564e+08
25  04.33.1171  model_2  1.485290e+06
26  05.66.3571  model_7  1.137485e+08
27  04.16.3439  model_1  1.272198e+07
28  05.15.2092  model_3  1.676450e+05
29  03.11.1141  model_4  6.633939e+07
30  04.22.1608  model_0  4.339200e+05
31  04.33.1125  model_2  3.366238e+06
32  05.15.3104  model_3  3.034079e+07
33  04.22.1448  model_0  3.060960e+07
34  05.15.2114  model_3  5.098909e+06
35  10.22.1770  model_0  2.579148e+06
36  10.22.1780  model_0  1.486527e+08
37  04.16.3569  model_1  1.717311e+07
38  04.22.1772  model_0  2.971532e+07
39  04.22.1170  model_0  3.439325e+07

In [70]:
train_e.groupby(['model_nm', 'fwver']).count().dropna().reset_index().sort_values('model_nm')

,model_nm,fwver,user_id,time,errtype,errcode,year,month,day,hour,minute
0,model_0,04.22.1684,5554.0,5554.0,5554.0,5554.0,5554.0,5554.0,5554.0,5554.0,5554.0
1,model_0,04.22.1750,2874213.0,2874213.0,2874213.0,2874213.0,2874213.0,2874213.0,2874213.0,2874213.0,2874213.0
2,model_0,04.22.1778,1293946.0,1293946.0,1293946.0,1293946.0,1293946.0,1293946.0,1293946.0,1293946.0,1293946.0
3,model_0,04.22.1666,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0
4,model_0,04.22.1442,2522.0,2522.0,2522.0,2522.0,2522.0,2522.0,2522.0,2522.0,2522.0
5,model_0,04.22.1656,39.0,39.0,39.0,39.0,39.0,39.0,39.0,39.0,39.0
11,model_1,04.16.3345,101.0,101.0,101.0,101.0,101.0,101.0,101.0,101.0,101.0
9,model_1,04.16.3569,980.0,980.0,980.0,980.0,980.0,980.0,980.0,980.0,980.0
10,model_1,04.16.2641,296.0,296.0,296.0,296.0,296.0,296.0,296.0,296.0,296.0
7,model_1,04.16.3571,145156.0,145156.0,145156.0,145156.0,145156.0,145156.0,145156.0,145156.0,145156.0
6,model_1,04.16.3553,5237816.0,5237816.0,5237816.0,5237816.0,5237816.0,5237816.0,5237816.0,5237816.0,5237816.0
8,model_1,04.16.3439,142.0,142.0,142.0,142.0,142.0,142.0,142.0,142.0,142.0
12,model_2,04.33.1149,3272.0,3272.0,3272.0,3272.0,3272.0,3272.0,3272.0,3272.0,3272.0
13,model_2,04.33.1171,58.0,58.0,58.0,58.0,58.0,58.0,58.0,58.0,58.0
14,model_2,04.33.1185,963736.0,963736.0,963736.0,963736.0,963736.0,963736.0,963736.0,963736.0,963736.0
15,model_2,04.33.1261,2504871.0,2504871.0,2504871.0,2504870.0,2504871.0,2504871.0,2504871.0,2504871.0,2504871.0
16,model_2,04.33.1125,408.0,408.0,408.0,408.0,408.0,408.0,408.0,408.0,408.0
17,model_2,04.33.1095,909.0,909.0,909.0,909.0,909.0,909.0,909.0,909.0,909.0
23,model_3,05.15.2114,9.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0
24,model_3,05.15.2092,18.0,18.0,18.0,18.0,18.0,18.0,18.0,18.0,18.0
22,model_3,05.15.2122,23.0,23.0,23.0,23.0,23.0,23.0,23.0,23.0,23.0
18,model_3,05.15.2138,1906479.0,1906479.0,1906479.0,1906479.0,1906479.0,1906479.0,1906479.0,1906479.0,1906479.0
20,model_3,05.15.2090,12.0,12.0,12.0,12.0,12.0,12.0,12.0,12.0,12.0
19,model_3,05.15.2120,706.0,706.0,706.0,706.0,706.0,706.0,706.0,706.0,706.0
21,model_3,05.15.3104,191.0,191.0,191.0,191.0,191.0,191.0,191.0,191.0,191.0
25,model_4,03.11.1149,2114.0,2114.0,2114.0,2114.0,2114.0,2114.0,2114.0,2114.0,2114.0
26,model_4,03.11.1167,1505659.0,1505659.0,1505659.0,1505659.0,1505659.0,1505659.0,1505659.0,1505659.0,1505659.0
27,model_4,03.11.1141,29.0,29.0,29.0,29.0,29.0,29.0,29.0,29.0,29.0
28,model_5,04.82.1684,23554.0,23554.0,23554.0,23554.0,23554.0,23554.0,23554.0,23554.0,23554.0
29,model_5,04.82.1778,8601.0,8601.0,8601.0,8601.0,8601.0,8601.0,8601.0,8601.0,8601.0
30,model_5,04.82.1730,78.0,78.0,78.0,78.0,78.0,78.0,78.0,78.0,78.0
31,model_7,05.66.3237,31832.0,31832.0,31832.0,31832.0,31832.0,31832.0,31832.0,31832.0,31832.0
32,model_7,05.66.3571,3524.0,3524.0,3524.0,3524.0,3524.0,3524.0,3524.0,3524.0,3524.0
33,model_8,04.73.2237,33537.0,33537.0,33537.0,33537.0,33537.0,33537.0,33537.0,33537.0,33537.0
34,model_8,04.73.2571,2527.0,2527.0,2527.0,2527.0,2527.0,2527.0,2527.0,2527.0,2527.0
35,model_6,10.10.1000,1534.0,1534.0,1534.0,1534.0,1534.0,1534.0,1534.0,1534.0,1534.0
36,model_6,8.5.3,212.0,212.0,212.0,212.0,212.0,212.0,212.0,212.0,212.0

In [32]:
test_e.groupby(['model_nm', 'fwver']).count().dropna().reset_index()

,model_nm,fwver,user_id,time,errtype,errcode,year,month,day,hour,minute
0,model_0,04.22.1684,4967.0,4967.0,4967.0,4967.0,4967.0,4967.0,4967.0,4967.0,4967.0
1,model_0,04.22.1750,2969638.0,2969638.0,2969638.0,2969638.0,2969638.0,2969638.0,2969638.0,2969638.0,2969638.0
2,model_0,04.22.1778,1368279.0,1368279.0,1368279.0,1368279.0,1368279.0,1368279.0,1368279.0,1368279.0,1368279.0
3,model_0,04.22.1478,535.0,535.0,535.0,535.0,535.0,535.0,535.0,535.0,535.0
4,model_0,04.22.1656,835.0,835.0,835.0,835.0,835.0,835.0,835.0,835.0,835.0
5,model_0,04.22.1666,43.0,43.0,43.0,43.0,43.0,43.0,43.0,43.0,43.0
6,model_0,04.22.1608,12.0,12.0,12.0,12.0,12.0,12.0,12.0,12.0,12.0
7,model_0,04.22.1448,840.0,840.0,840.0,840.0,840.0,840.0,840.0,840.0,840.0
8,model_0,10.22.1770,66.0,66.0,66.0,66.0,66.0,66.0,66.0,66.0,66.0
9,model_0,10.22.1780,3804.0,3804.0,3804.0,3804.0,3804.0,3804.0,3804.0,3804.0,3804.0
10,model_0,04.22.1772,735.0,735.0,735.0,735.0,735.0,735.0,735.0,735.0,735.0
11,model_0,04.22.1170,817.0,817.0,817.0,817.0,817.0,817.0,817.0,817.0,817.0
12,model_1,04.16.3553,5326124.0,5326124.0,5326124.0,5326123.0,5326124.0,5326124.0,5326124.0,5326124.0,5326124.0
13,model_1,04.16.3571,146942.0,146942.0,146942.0,146942.0,146942.0,146942.0,146942.0,146942.0,146942.0
14,model_1,04.16.3439,379.0,379.0,379.0,379.0,379.0,379.0,379.0,379.0,379.0
15,model_1,04.16.3569,402.0,402.0,402.0,402.0,402.0,402.0,402.0,402.0,402.0
16,model_2,04.33.1149,6045.0,6045.0,6045.0,6045.0,6045.0,6045.0,6045.0,6045.0,6045.0
17,model_2,04.33.1185,987893.0,987893.0,987893.0,987892.0,987893.0,987893.0,987893.0,987893.0,987893.0
18,model_2,04.33.1261,2607195.0,2607195.0,2607195.0,2607193.0,2607195.0,2607195.0,2607195.0,2607195.0,2607195.0
19,model_2,04.33.1171,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0,40.0
20,model_2,04.33.1125,85.0,85.0,85.0,85.0,85.0,85.0,85.0,85.0,85.0
21,model_3,05.15.2120,425.0,425.0,425.0,425.0,425.0,425.0,425.0,425.0,425.0
22,model_3,05.15.2138,1800062.0,1800062.0,1800062.0,1800062.0,1800062.0,1800062.0,1800062.0,1800062.0,1800062.0
23,model_3,05.15.2092,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0
24,model_3,05.15.3104,837.0,837.0,837.0,837.0,837.0,837.0,837.0,837.0,837.0
25,model_3,05.15.2114,123.0,123.0,123.0,123.0,123.0,123.0,123.0,123.0,123.0
26,model_4,03.11.1167,1209675.0,1209675.0,1209675.0,1209675.0,1209675.0,1209675.0,1209675.0,1209675.0,1209675.0
27,model_4,03.11.1149,4552.0,4552.0,4552.0,4552.0,4552.0,4552.0,4552.0,4552.0,4552.0
28,model_4,03.11.1141,1569.0,1569.0,1569.0,1569.0,1569.0,1569.0,1569.0,1569.0,1569.0
29,model_5,04.82.1684,23184.0,23184.0,23184.0,23184.0,23184.0,23184.0,23184.0,23184.0,23184.0
30,model_5,04.82.1778,12010.0,12010.0,12010.0,12010.0,12010.0,12010.0,12010.0,12010.0,12010.0
31,model_5,04.82.1730,268.0,268.0,268.0,268.0,268.0,268.0,268.0,268.0,268.0
32,model_6,10.10.1000,561.0,561.0,561.0,561.0,561.0,561.0,561.0,561.0,561.0
33,model_6,8.5.3,13.0,13.0,13.0,13.0,13.0,13.0,13.0,13.0,13.0
34,model_7,05.66.3237,25691.0,25691.0,25691.0,25691.0,25691.0,25691.0,25691.0,25691.0,25691.0
35,model_7,05.66.3571,3003.0,3003.0,3003.0,3003.0,3003.0,3003.0,3003.0,3003.0,3003.0
36,model_8,04.73.2237,20433.0,20433.0,20433.0,20433.0,20433.0,20433.0,20433.0,20433.0,20433.0
37,model_8,04.73.2569,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0,17.0
38,model_8,04.73.2571,4491.0,4491.0,4491.0,4491.0,4491.0,4491.0,4491.0,4491.0,4491.0
39,model_8,04.73.2577,53.0,53.0,53.0,53.0,53.0,53.0,53.0,53.0,53.0

In [46]:
train_e.groupby(['model_nm', 'errtype'])['errtype'].count().unstack()

errtype,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,30,31,32,33,34,35,36,37,38,39,40,41,42
model_nm,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
model_0,108,3775,0,2596,395563,10164,12037,47,47,20325,85231,87733,2911,54128,545830,394076,5340,958,249,841,248,617067,574183,10960,645,158050,1621,1625,123,737022,4402,68781,71144,3391,4249,4253,1432,8222,243220,35289,8393
model_1,69,655,3,2720,220544,8985,9807,10,23,15059,56414,59574,8439,37596,272336,218642,25268,340,108,292,108,993653,1490911,16651,223,78966,943,947,53,521305,1110834,42544,47470,2359,960,961,1450,2175,120399,14446,249
model_2,78,18161,0,284,303689,14847,15759,43,26,6670,72628,76331,6983,75087,519375,373806,7160,1034,242,920,243,249246,206188,3713,305,211279,982,988,101,718178,13039,66566,44839,4390,4041,4056,1499,5370,365314,54086,25708
model_3,208,3363,29483,998177,14762,12606,12068,33,12,85283,74734,78023,3689,71637,212525,212155,3994,308,57,0,0,0,0,7666,0,83154,1703,1705,93,0,0,0,0,0,0,0,0,0,0,0,0
model_4,21082,0,881,282871,1081,3637,2031,31,1,5584,15161,15530,548,3499,39393,38094,3778,0,0,0,0,0,0,0,0,0,535547,539033,20,0,0,0,0,0,0,0,0,0,0,0,0
model_5,0,122,0,16,4766,88,104,0,0,21,699,726,30,161,5106,3725,68,6,1,6,1,1734,989,7,0,1376,8,8,4,7981,318,519,1640,40,40,39,150,53,1359,301,21
model_7,0,0,326,5733,5118,111,142,2,0,375,1413,1496,101,670,5656,4790,123,17,6,15,6,2025,2905,30,8,2035,0,0,4,510,1347,36,262,3,15,15,4,0,38,16,3
model_8,0,30,65,4353,5651,44,45,0,0,86,750,768,142,9237,4730,4088,278,8,1,6,1,1636,1339,44,3,1541,0,0,4,298,624,31,181,4,12,12,4,0,48,0,0
model_6,0,0,0,0,1746,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [47]:
train_e.groupby(['fwver', 'errtype'])['errtype'].count().unstack()

errtype,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,30,31,32,33,34,35,36,37,38,39,40,41,42
fwver,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
03.11.1149,90,0,0,399,26,29,11,0,0,0,0,3,0,14,0,0,0,0,0,0,0,0,0,0,0,0,767,775,0,0,0,0,0,0,0,0,0,0,0,0,0
03.11.1167,20989,0,881,282472,1054,3605,2018,31,1,5584,15161,15527,548,3482,39393,38094,3778,0,0,0,0,0,0,0,0,0,534772,538250,19,0,0,0,0,0,0,0,0,0,0,0,0
04.16.3553,69,627,0,2596,215494,8868,9686,10,23,14731,54873,57994,8404,35899,264147,212222,24619,282,82,251,82,970609,1468296,16589,171,74951,931,934,47,506653,1073268,41282,36267,2304,452,453,1371,1633,116527,13965,154
04.16.3571,0,28,0,0,5049,113,114,0,0,324,1506,1544,34,1683,8085,6319,648,58,26,41,26,22716,22251,62,52,3960,10,11,6,14550,37367,1250,11193,54,508,508,77,542,3868,481,92
04.22.1684,1,0,0,7,1321,22,28,0,0,20,23,29,9,291,139,134,8,1,0,2,0,22,21,0,1,15,11,11,0,2930,0,4,54,15,0,0,131,0,273,31,0
04.22.1750,83,2461,0,2075,279747,7255,8961,40,26,14541,58650,60456,1988,41722,378368,273167,3051,645,165,574,164,418553,406403,8171,439,83823,987,993,85,510162,3104,46718,54132,2408,83,90,1009,5632,173898,23316,68
04.22.1778,24,1314,0,24,114488,2873,3037,7,21,5763,26498,27179,900,12098,167034,120600,2281,310,84,264,84,197832,167060,2789,204,74159,622,620,38,223930,1298,22059,16958,968,4166,4163,291,2590,69049,11942,8325
04.33.1149,1,0,0,0,316,14,14,0,0,4,88,94,6,44,534,279,5,23,1,23,1,131,68,0,0,122,0,0,2,654,0,182,188,3,0,10,32,6,332,95,0
04.33.1171,0,0,0,0,0,0,1,0,0,0,1,1,0,5,6,4,0,1,0,1,0,0,0,0,0,2,0,0,0,28,0,3,0,0,0,0,0,0,4,1,0
04.33.1185,11,10869,0,13,89893,4724,5076,7,18,2122,19547,20751,1783,19287,142533,101166,1636,247,33,223,33,71001,66507,502,56,34059,311,315,28,197251,4078,17509,11380,1367,195,201,478,1206,122581,14724,15
04.33.1261,66,7292,0,5,213373,10106,10660,36,8,4544,52894,55382,5193,55747,375954,272155,5516,758,208,668,209,178041,139602,3211,249,177016,671,673,71,520245,8961,48872,33271,3020,3846,3845,989,4158,242397,39266,25693
04.82.1684,0,110,0,16,3464,66,88,0,0,14,503,528,28,116,3706,2730,54,6,1,6,1,1046,701,6,0,821,6,6,4,6059,232,329,1410,30,0,0,147,47,1053,220,0
04.82.1778,0,12,0,0,1301,18,12,0,0,5,193,193,1,36,1389,989,14,0,0,0,0,682,277,1,0,552,2,2,0,1912,86,188,230,10,40,39,3,6,306,81,21
05.15.2138,208,3363,29426,997780,14746,12590,12050,33,12,85225,74641,77923,3683,71560,212502,212131,3994,305,57,0,0,0,0,7664,0,83089,1701,1703,93,0,0,0,0,0,0,0,0,0,0,0,0
05.66.3237,0,0,326,5733,4823,105,137,2,0,374,1376,1454,94,656,5380,4566,105,17,6,15,6,1874,2836,30,8,1906,0,0,3,0,0,0,0,0,0,0,0,0,0,0,0
05.66.3571,0,0,0,0,295,6,5,0,0,1,37,42,7,14,276,224,18,0,0,0,0,151,69,0,0,129,0,0,1,510,1347,36,262,3,15,15,4,0,38,16,3
04.73.2237,0,30,65,4353,4973,42,43,0,0,86,719,734,138,9231,4543,3952,255,5,0,4,0,1564,1314,43,1,1438,0,0,4,0,0,0,0,0,0,0,0,0,0,0,0
10.10.1000,0,0,0,0,1534,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
04.82.1730,0,0,0,0,1,4,4,0,0,2,3,5,1,9,11,6,0,0,0,0,0,6,11,0,0,3,0,0,0,10,0,2,0,0,0,0,0,0,0,0,0
04.73.2571,0,0,0,0,678,2,2,0,0,0,31,34,4,6,187,136,23,3,1,2,1,72,25,1,2,103,0,0,0,298,624,31,181,4,12,12,4,0,48,0,0
8.5.3,0,0,0,0,212,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
04.22.1666,0,0,0,0,0,0,0,0,0,0,0,1,1,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
03.11.1141,3,0,0,0,1,3,2,0,0,0,0,0,0,3,0,0,0,0,0,0,0,0,0,0,0,0,8,8,1,0,0,0,0,0,0,0,0,0,0,0,0
05.15.2120,0,0,43,338,4,9,11,0,0,46,44,48,4,59,18,21,0,0,0,0,0,0,0,2,0,57,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0
04.33.1125,0,0,0,97,1,2,3,0,0,0,36,39,0,3,94,43,1,5,0,5,0,37,6,0,0,36,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
04.16.3439,0,0,0,0,0,2,2,0,0,0,2,2,0,5,1,7,0,0,0,0,0,31,37,0,0,2,2,2,0,32,0,7,1,1,0,0,2,0,4,0,0
04.22.1442,0,0,0,486,6,9,6,0,0,1,59,66,10,10,286,173,0,2,0,1,0,658,696,0,1,52,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
04.33.1095,0,0,0,169,106,1,5,0,0,0,62,64,1,1,254,159,2,0,0,0,0,36,5,0,0,44,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
04.16.3569,0,0,0,0,1,0,0,0,0,1,5,5,0,0,36,32,1,0,0,0,0,273,324,0,0,16,0,0,0,70,199,5,9,0,0,0,0,0,0,0,3
05.15.2090,0,0,1,0,2,1,1,0,0,1,2,2,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
05.15.3104,0,0,12,43,8,5,5,0,0,11,42,44,1,14,3,2,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
05.15.2122,0,0,0,6,1,0,0,0,0,0,4,4,0,0,1,1,0,3,0,0,0,0,0,0,0,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
04.22.1656,0,0,0,4,1,5,5,0,0,0,1,2,3,5,3,2,0,0,0,0,0,2,3,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0
04.16.2641,0,0,1,81,0,2,5,0,0,0,19,20,1,7,53,52,0,0,0,0,0,24,3,0,0,28,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
05.15.2114,0,0,0,4,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
04.16.3345,0,0,2,43,0,0,0,0,0,3,9,9,0,2,14,10,0,0,0,0,0,0,0,0,0,9,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
05.15.2092,0,0,1,6,1,1,1,0,0,0,1,2,1,2,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0

In [73]:
train_b_p

       user_id  target
0        10000       0
1        10001       1
2        10002       0
3        10003       0
4        10004       1
...        ...     ...
14995    24995       0
14996    24996       0
14997    24997       1
14998    24998       1
14999    24999       0

[15000 rows x 2 columns]

In [89]:
train_e

,user_id,time,model_nm,fwver,errtype,errcode,year,month,day,hour,minute
0,10000,2020-11-01 02:00:00,model_3,05.15.2138,15,1,2020,11,01,02,00
1,10000,2020-11-01 03:00:00,model_3,05.15.2138,12,1,2020,11,01,03,00
2,10000,2020-11-01 03:00:00,model_3,05.15.2138,11,1,2020,11,01,03,00
3,10000,2020-11-01 05:00:00,model_3,05.15.2138,16,1,2020,11,01,05,00
4,10000,2020-11-01 05:00:00,model_3,05.15.2138,4,0,2020,11,01,05,00
...,...,...,...,...,...,...,...,...,...,...,...
16554658,24999,2020-11-30 16:00:00,model_3,05.15.2138,15,1,2020,11,30,16,00
16554659,24999,2020-11-30 17:00:00,model_3,05.15.2138,16,1,2020,11,30,17,00
16554660,24999,2020-11-30 17:00:00,model_3,05.15.2138,4,0,2020,11,30,17,00
16554661,24999,2020-11-30 17:00:00,model_3,05.15.2138,4,0,2020,11,30,17,00
16554662,24999,2020-11-30 21:00:00,model_3,05.15.2138,15,1,2020,11,30,21,00

In [122]:
train_e.groupby(['hour','errtype'])['errtype'].count().unstack().fillna(0)

errtype,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,30,31,32,33,34,35,36,37,38,39,40,41,42
hour,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
00,91.0,1640.0,1025.0,46989.0,40875.0,1750.0,1712.0,5.0,1.0,31690.0,4708.0,4846.0,873.0,10081.0,73849.0,25269.0,1272.0,23.0,16.0,21.0,16.0,67577.0,90924.0,1489.0,18.0,146101.0,14544.0,14735.0,0.0,47978.0,52679.0,1098.0,4077.0,391.0,38.0,38.0,177.0,1131.0,28712.0,3894.0,17.0
01,48.0,1575.0,1061.0,43735.0,26982.0,1889.0,1711.0,5.0,4.0,3169.0,4014.0,4347.0,813.0,8229.0,45575.0,16540.0,539.0,22.0,12.0,13.0,12.0,54669.0,72663.0,1181.0,13.0,21237.0,12947.0,13036.0,0.0,33218.0,54191.0,817.0,2544.0,291.0,20.0,20.0,111.0,844.0,20156.0,2039.0,10.0
02,4874.0,926.0,1033.0,49389.0,20453.0,2000.0,1989.0,0.0,1.0,9564.0,45338.0,45709.0,937.0,8608.0,121253.0,12350.0,392.0,12.0,4.0,8.0,4.0,94828.0,70801.0,1232.0,15.0,10299.0,15679.0,15786.0,0.0,42861.0,49223.0,32287.0,1340.0,253.0,1769.0,1769.0,96.0,815.0,17053.0,1193.0,9025.0
03,4814.0,777.0,1204.0,49491.0,15700.0,2307.0,2063.0,0.0,0.0,3693.0,49176.0,49649.0,817.0,10429.0,120837.0,11390.0,532.0,4.0,1.0,4.0,1.0,94043.0,67488.0,1157.0,3.0,8231.0,17487.0,17665.0,0.0,41694.0,53642.0,34695.0,1246.0,207.0,2120.0,2117.0,79.0,404.0,11506.0,757.0,9530.0
04,5047.0,634.0,1361.0,51680.0,13469.0,1951.0,1917.0,0.0,1.0,2950.0,50550.0,51066.0,993.0,10758.0,120680.0,14945.0,570.0,4.0,1.0,3.0,1.0,91066.0,61076.0,1320.0,0.0,10485.0,17693.0,17934.0,0.0,43906.0,44430.0,35735.0,1170.0,98.0,2263.0,2265.0,91.0,353.0,11232.0,615.0,10111.0
05,2600.0,499.0,1748.0,54072.0,12153.0,2517.0,2503.0,0.0,2.0,2786.0,28990.0,30197.0,1454.0,11112.0,73448.0,26291.0,1154.0,5.0,4.0,4.0,4.0,62097.0,51706.0,1090.0,0.0,19031.0,19819.0,19918.0,0.0,45654.0,39647.0,19494.0,1339.0,83.0,1418.0,1421.0,88.0,312.0,14260.0,569.0,4857.0
06,141.0,385.0,1488.0,55515.0,12162.0,2193.0,2163.0,3.0,3.0,2751.0,5536.0,6596.0,1462.0,10557.0,29009.0,48502.0,2665.0,16.0,12.0,7.0,5.0,39487.0,51203.0,1107.0,4.0,34024.0,17649.0,17851.0,1.0,62428.0,37075.0,2307.0,3154.0,118.0,176.0,176.0,98.0,268.0,21807.0,763.0,10.0
07,186.0,582.0,1560.0,64503.0,21078.0,2323.0,2280.0,0.0,1.0,2881.0,6941.0,8048.0,1580.0,10937.0,46004.0,78625.0,4580.0,19.0,6.0,9.0,6.0,50128.0,65812.0,1459.0,20.0,51775.0,21606.0,21756.0,0.0,104694.0,39719.0,3512.0,5422.0,158.0,162.0,164.0,160.0,435.0,32080.0,2032.0,18.0
08,233.0,897.0,1050.0,61840.0,30404.0,1751.0,1661.0,2.0,2.0,3028.0,7068.0,7541.0,902.0,9965.0,64069.0,79518.0,4258.0,67.0,28.0,46.0,26.0,64395.0,86004.0,1589.0,36.0,44162.0,21387.0,21479.0,1.0,111260.0,42441.0,3248.0,7517.0,244.0,117.0,116.0,154.0,524.0,35753.0,3749.0,33.0
09,186.0,598.0,1120.0,58227.0,39128.0,1859.0,1750.0,8.0,1.0,2973.0,6724.0,7157.0,1073.0,10828.0,61565.0,64650.0,3052.0,147.0,33.0,114.0,32.0,67380.0,89938.0,1496.0,86.0,29165.0,24723.0,24922.0,32.0,96318.0,40916.0,3141.0,7357.0,387.0,131.0,132.0,176.0,573.0,33654.0,4069.0,40.0
10,202.0,1232.0,1190.0,55130.0,42253.0,2085.0,2088.0,13.0,4.0,3073.0,6528.0,7020.0,1610.0,10652.0,55152.0,54125.0,2119.0,284.0,36.0,222.0,30.0,66957.0,89280.0,1314.0,79.0,18805.0,25634.0,25785.0,36.0,82871.0,40603.0,2850.0,7978.0,505.0,136.0,139.0,186.0,441.0,30439.0,4348.0,38.0
11,192.0,816.0,1204.0,52738.0,46074.0,2091.0,3457.0,15.0,6.0,2909.0,6190.0,6711.0,795.0,10990.0,52217.0,50784.0,1857.0,218.0,34.0,174.0,28.0,66113.0,88646.0,1575.0,51.0,13818.0,26328.0,26419.0,35.0,80087.0,41606.0,2635.0,7691.0,539.0,108.0,110.0,201.0,455.0,28658.0,4726.0,35.0
12,194.0,733.0,1082.0,50903.0,48277.0,2079.0,2385.0,5.0,4.0,3119.0,6243.0,6644.0,769.0,11103.0,54189.0,54301.0,1550.0,155.0,32.0,116.0,30.0,68539.0,92713.0,1660.0,53.0,12173.0,25539.0,25658.0,26.0,85926.0,44235.0,2654.0,8441.0,467.0,80.0,81.0,168.0,372.0,28237.0,5260.0,34.0
13,205.0,802.0,1158.0,51802.0,50370.0,2392.0,2612.0,7.0,17.0,3505.0,6619.0,7153.0,823.0,11941.0,56451.0,52616.0,1497.0,248.0,36.0,200.0,31.0,70160.0,93742.0,1609.0,72.0,9933.0,27585.0,27724.0,40.0,84488.0,45958.0,2726.0,8883.0,609.0,110.0,112.0,203.0,396.0,30131.0,5563.0,26.0
14,271.0,586.0,1252.0,49456.0,49858.0,2402.0,2461.0,5.0,2.0,3144.0,6277.0,6801.0,771.0,10577.0,53225.0,51189.0,1352.0,214.0,31.0,165.0,29.0,68103.0,90505.0,1403.0,78.0,8471.0,25694.0,25783.0,38.0,83419.0,45185.0,2638.0,7779.0,600.0,88.0,89.0,157.0,469.0,29800.0,5403.0,29.0
15,288.0,825.0,1260.0,51923.0,47035.0,2259.0,2294.0,10.0,5.0,2656.0,6374.0,6970.0,765.0,10490.0,52865.0,55544.0,1536.0,213.0,38.0,184.0,36.0,69350.0,92011.0,1563.0,61.0,8647.0,26755.0,26931.0,38.0,89597.0,47116.0,2914.0,7091.0,528.0,103.0,104.0,189.0,588.0,31074.0,5193.0,38.0
16,285.0,1055.0,1307.0,54647.0,47094.0,2229.0,2333.0,8.0,5.0,3039.0,7101.0,7616.0,737.0,10073.0,53993.0,66580.0,1657.0,200.0,30.0,149.0,27.0,73042.0,96127.0,1785.0,64.0,9889.0,25777.0,25887.0,42.0,104983.0,49428.0,3262.0,9585.0,511.0,94.0,95.0,260.0,701.0,34165.0,6069.0,46.0
17,258.0,977.0,1300.0,57752.0,46604.0,2117.0,2164.0,5.0,5.0,3284.0,7889.0,8439.0,846.0,9851.0,57224.0,80489.0,1723.0,212.0,52.0,174.0,45.0,81338.0,106342.0,1893.0,102.0,12865.0,26094.0,26204.0,33.0,123603.0,48976.0,4063.0,8479.0,592.0,94.0,95.0,270.0,479.0,38833.0,5929.0,63.0
18,310.0,2132.0,1300.0,61578.0,50958.0,2114.0,2093.0,1.0,11.0,3254.0,8417.0,8967.0,859.0,10165.0,60051.0,87372.0,2245.0,158.0,45.0,124.0,41.0,94564.0,123348.0,2259.0,73.0,15732.0,32368.0,32517.0,12.0,130920.0,48553.0,4286.0,11402.0,513.0,98.0,99.0,290.0,685.0,41774.0,6825.0,77.0
19,322.0,1848.0,1515.0,62845.0,61183.0,2029.0,2124.0,13.0,12.0,4125.0,8751.0,9276.0,865.0,11268.0,60729.0,82890.0,2603.0,132.0,65.0,100.0,61.0,108403.0,142923.0,2425.0,53.0,15572.0,35955.0,36127.0,18.0,122564.0,50873.0,3807.0,14354.0,585.0,62.0,62.0,326.0,842.0,43737.0,7821.0,85.0
20,250.0,1410.0,1428.0,56185.0,61588.0,1979.0,2046.0,6.0,14.0,3723.0,8073.0,8585.0,746.0,11088.0,61772.0,72196.0,2414.0,106.0,46.0,79.0,43.0,112829.0,149707.0,2180.0,66.0,12777.0,23872.0,24012.0,13.0,107548.0,52598.0,3313.0,13830.0,690.0,40.0,42.0,294.0,688.0,42396.0,7772.0,85.0
21,223.0,1330.0,1550.0,56733.0,64358.0,2024.0,2050.0,7.0,3.0,3802.0,7540.0,8029.0,945.0,11166.0,74405.0,68207.0,2631.0,59.0,29.0,46.0,29.0,110060.0,147524.0,2284.0,72.0,10662.0,21480.0,21685.0,11.0,104151.0,54746.0,2869.0,10476.0,610.0,29.0,29.0,325.0,1124.0,45547.0,7402.0,73.0
22,193.0,1797.0,1501.0,52656.0,55492.0,2099.0,2116.0,34.0,1.0,3622.0,6645.0,7089.0,759.0,10786.0,77369.0,56592.0,2301.0,79.0,42.0,62.0,39.0,102691.0,137470.0,2172.0,74.0,7902.0,18234.0,18429.0,18.0,89679.0,53832.0,2487.0,7983.0,671.0,45.0,45.0,268.0,1439.0,43249.0,6890.0,49.0
23,132.0,2050.0,1061.0,46961.0,49372.0,2043.0,2021.0,14.0,4.0,24663.0,5338.0,5725.0,649.0,10361.0,79020.0,38411.0,1510.0,74.0,31.0,56.0,31.0,87542.0,118562.0,1829.0,91.0,4645.0,15955.0,16063.0,8.0,65447.0,52892.0,1639.0,6398.0,537.0,16.0,16.0,172.0,1482.0,36125.0,5257.0,45.0

In [80]:
temp = train_e.groupby(['user_id', 'fwver'])['errcode'].count().reset_index()

In [83]:
temp_2 = temp[temp.errcode != 0]

In [90]:
temp_3 = pd.merge(train_e, train_b_p, how='outer', on=['user_id'])

In [105]:
temp_4 = temp_3.groupby(['fwver', 'user_id'])['target'].max().reset_index()

In [117]:
temp_5 = temp_3.groupby(['model_nm', 'user_id'])['target'].max().reset_index()

In [111]:
temp_4.groupby('fwver').sum()

              user_id  target
fwver
03.11.1149  262492500     0.0
03.11.1167  262492500   141.0
04.16.3553  262492500  1314.0
04.16.3571  262492500   295.0
04.22.1684  262492500    28.0
04.22.1750  262492500  1630.0
04.22.1778  262492500  1586.0
04.33.1149  262492500   112.0
04.33.1171  262492500     1.0
04.33.1185  262492500  1128.0
04.33.1261  262492500  1739.0
04.82.1684  262492500    19.0
04.82.1778  262492500    20.0
05.15.2138  262492500   720.0
05.66.3237  262492500    32.0
05.66.3571  262492500     8.0
04.73.2237  262492500    22.0
10.10.1000  262492500     9.0
04.82.1730  262492500     1.0
04.73.2571  262492500     8.0
8.5.3       262492500     0.0
04.22.1666  262492500     0.0
03.11.1141  262492500     1.0
05.15.2120  262492500     2.0
04.33.1125  262492500     4.0
04.16.3439  262492500     2.0
04.22.1442  262492500     1.0
04.33.1095  262492500     0.0
04.16.3569  262492500     2.0
05.15.2090  262492500     0.0
05.15.3104  262492500     1.0
05.15.2122  262492500     0.0
04.22.1656  262492500     1.0
04.16.2641  262492500     1.0
05.15.2114  262492500     0.0
04.16.3345  262492500     1.0
05.15.2092  262492500     1.0

In [118]:
temp_5.groupby('model_nm').sum()

            user_id  target
model_nm
model_0   262492500  1637.0
model_1   262492500  1318.0
model_2   262492500  1744.0
model_3   262492500   720.0
model_4   262492500   141.0
model_5   262492500    20.0
model_7   262492500    32.0
model_8   262492500    22.0
model_6   262492500     9.0