노트북이 너무 쌓이면 새로운 노트북으로 갈아타줍니다.

# 변수 모으기 2

# IMPORT & LOAD DATA

In [1]:
import load_dtypes as ld
import warnings
warnings.filterwarnings(action='ignore')

import os, sys
import time
import datetime as dt

import numpy as np
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)

import matplotlib.pyplot as plt
import seaborn as sns

from tqdm import tqdm

from imblearn.over_sampling import SMOTE, BorderlineSMOTE, ADASYN

from sklearn.model_selection import train_test_split
from sklearn.metrics import auc, roc_auc_score, roc_curve, precision_recall_curve, recall_score, precision_score

import lightgbm as lgb
from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.model_selection import StratifiedKFold

In [2]:
#-------------------------------------------------------------------------------------
# validation auc score를 확인하기 위해 정의
def f_pr_auc(probas_pred, y_true):
    labels=y_true.get_label()
    p, r, _ = precision_recall_curve(labels, probas_pred)
    score=auc(r,p) 
    return "pr_auc", score, True
#-------------------------------------------------------------------------------------

In [3]:
TRAIN_P_PATH = r'C:\Users\Wyatt\wyatt37/Data/systemError/train_problem_data.csv'
TRAIN_Q_PATH = r'C:\Users\Wyatt\wyatt37/Data/systemError/train_quality_data.csv'
TRAIN_E_PATH = r'C:\Users\Wyatt\wyatt37/Data/systemError/train_err_data.csv'
TEST_Q_PATH = r'C:\Users\Wyatt\wyatt37/Data/systemError/test_quality_data.csv'
TEST_E_PATH = r'C:\Users\Wyatt\wyatt37/Data/systemError/test_err_data.csv'
SUBMISSION_PATH = r'C:\Users\Wyatt\wyatt37/Data/systemError/sample_submission.csv'

In [4]:
%%time
train_p = ld.load_dtypes(TRAIN_P_PATH)
train_q = ld.load_dtypes(TRAIN_Q_PATH)
train_e = ld.load_dtypes(TRAIN_E_PATH)
test_q = ld.load_dtypes(TEST_Q_PATH)
test_e = ld.load_dtypes(TEST_E_PATH)
submission = pd.read_csv(SUBMISSION_PATH)

C:\Users\Wyatt\wyatt37/Data/systemError/train_problem_data.csv
C:\Users\Wyatt\wyatt37/Data/systemError/train_quality_data.csv
C:\Users\Wyatt\wyatt37/Data/systemError/train_err_data.csv
C:\Users\Wyatt\wyatt37/Data/systemError/test_quality_data.csv
C:\Users\Wyatt\wyatt37/Data/systemError/test_err_data.csv
Wall time: 1min 16s

In [5]:
train_p.shape, train_q.shape, train_e.shape, test_q.shape, test_e.shape, submission.shape

((5429, 2),
 (828624, 16),
 (16554663, 6),
 (747972, 16),
 (16532648, 6),
 (14999, 2))

In [6]:
train_p.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5429 entries, 0 to 5428
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   user_id  5429 non-null   int16
 1   time     5429 non-null   int64
dtypes: int16(1), int64(1)
memory usage: 53.1 KB

In [7]:
train_q.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 828624 entries, 0 to 828623
Data columns (total 16 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   time        828624 non-null  int64
 1   user_id     828624 non-null  int16
 2   fwver       788544 non-null  category
 3   quality_0   684192 non-null  float32
 4   quality_1   828624 non-null  int16
 5   quality_2   788511 non-null  float32
 6   quality_3   828624 non-null  int8
 7   quality_4   828624 non-null  int8
 8   quality_5   828604 non-null  category
 9   quality_6   828624 non-null  int16
 10  quality_7   828624 non-null  category
 11  quality_8   828624 non-null  category
 12  quality_9   828624 non-null  category
 13  quality_10  828624 non-null  category
 14  quality_11  828624 non-null  int8
 15  quality_12  828624 non-null  int8
dtypes: category(6), float32(2), int16(3), int64(1), int8(4)
memory usage: 28.9 MB

In [8]:
train_e.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16554663 entries, 0 to 16554662
Data columns (total 6 columns):
 #   Column    Dtype
---  ------    -----
 0   user_id   int16
 1   time      int64
 2   model_nm  category
 3   fwver     category
 4   errtype   int8
 5   errcode   category
dtypes: category(3), int16(1), int64(1), int8(1)
memory usage: 236.9 MB

In [9]:
test_q.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 747972 entries, 0 to 747971
Data columns (total 16 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   time        747972 non-null  int64
 1   user_id     747972 non-null  uint16
 2   fwver       725208 non-null  category
 3   quality_0   641388 non-null  float32
 4   quality_1   747961 non-null  category
 5   quality_2   726857 non-null  float32
 6   quality_3   747972 non-null  int8
 7   quality_4   747972 non-null  int8
 8   quality_5   747928 non-null  category
 9   quality_6   747972 non-null  int16
 10  quality_7   747972 non-null  category
 11  quality_8   747972 non-null  category
 12  quality_9   747972 non-null  category
 13  quality_10  747972 non-null  category
 14  quality_11  747972 non-null  int8
 15  quality_12  747972 non-null  int8
dtypes: category(7), float32(2), int16(1), int64(1), int8(4), uint16(1)
memory usage: 25.4 MB

In [10]:
test_e.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16532648 entries, 0 to 16532647
Data columns (total 6 columns):
 #   Column    Dtype
---  ------    -----
 0   user_id   uint16
 1   time      int64
 2   model_nm  category
 3   fwver     category
 4   errtype   int8
 5   errcode   category
dtypes: category(3), int64(1), int8(1), uint16(1)
memory usage: 236.6 MB

In [11]:
def preprocessing_problem(df, object_='binary'):
    """
    definition:
    train_problem 테이블을 받아서 target 값으로 변환
    1. {0, 1}의 binary로 변환
    2. {0 ~ n}의 multiclass로 변환
    """
    
    # 10001부터 24999까지의 index를 만들어줍니다.
    user_id_idx = np.array(range(10000, 25000, 1))
    
    # train_new_p라는 새로운 df를 만들고 index는 위에서 만든 user_id_idx 로 지정해줍니다.
    new_p = pd.DataFrame(index = user_id_idx)
    new_p['target'] = 0
    
    if object_ == 'binary':
        new_p.iloc[df.user_id.unique()-10000] = 1
        new_p = new_p.reset_index()
        new_p.rename({'index':'user_id'}, axis=1, inplace=True)
        
    elif object_ == 'multi':
        # multi는 count()로 집계를 해줍니다.
        new_p['target'] = df.groupby('user_id')['time'].count()
        new_p = new_p.fillna(0)
        new_p = new_p.reset_index()
        new_p.rename({'index':'user_id'}, axis=1, inplace=True)
        
    return new_p

In [12]:
train_b_p = preprocessing_problem(train_p, 'binary')
train_m_p = preprocessing_problem(train_p, 'multi')

In [13]:
def preprocessing_quality(df):
    """
    definition:
    EDA를 통해 알아낸 정보로 train_q, test_q를 정리해서 내뿜어줍니다.
    1. qaulity_3, quality_4 를 drop 합니다.(단일 value)
    2. qaulity_k 변수들을 정수로 encoding 합니다.
    """
    # 먼저 3, 4번을 drop 합니다.
    df.drop(['quality_3', 'quality_4'], axis=1, inplace=True)
    
    # qual 변수만 할당해주고, 정수로 형변환 해줍니다.
    columns = train_q.columns[train_q.columns.str.contains('quality')]
    # for문을 통해 각 column을 반복 작업해줍니다.
    for col in columns:
        try:
            if df[col].dtype == 'float32': # 기존에 float은 패스
                df[col] = df[col].fillna(-2)
            elif df[col].dtype == 'int8' or df[col].dtype == 'int16': # 기존에 int도 패스
                df[col] = df[col].fillna(-2)
                #print(col)
            else:
                df[col] = df[col].astype('object')
                # nan값이 있으면 float으로 갈 수 없으니 '-2' 으로 채워줍니다.
                df[col] = df[col].fillna('-2')
                df[col] = df[col].apply(lambda x: x.replace(',' , ''))
                df[col] = df[col].astype(np.float32)
        except:
            pass
        
    # fwver 에서 null 값이 꽤 있습니다. missing으로 채우겠습니다.
    df.fwver = df.fwver.astype('object')
    df.fwver = df.fwver.fillna('missing')
    df.fwver = df.fwver.astype('category')
        
    return df

In [14]:
train_q = preprocessing_quality(train_q)
test_q = preprocessing_quality(test_q)

In [15]:
def preprocessing_fwver(df):
    """
    definition:
    별건 아니고, e-set에 fwver 변수에서 '10' 이라는 값이 있는데, 이게 errtype이랑 겹쳐요.
    그래서 10을 -> 8.5.2 으로 바꿔줄 겁니다.
    굳이 이렇게 바꾸는 이유는, 해당 fw가 8.5.3버전과 같은 model_nm을 공유하기 때문입니다.
    """
    df.fwver = df.fwver.replace('10', '8.5.2')
        
    return df

In [16]:
train_e = preprocessing_fwver(train_e)
test_e = preprocessing_fwver(test_e)

In [17]:
def make_datetime(df):
    """
    definition:
    'time' column이 str로 되어 있으니, datetime으로 바꿔주는 함수입니다.
    다만 'time'양식이 pandas함수에 적용이 안되니, 강제로 슬라이싱해서 만들어줘야 합니다.
    
    """
    
    df['year'] = df['time'].apply(lambda x: str(x)[:4])
    df['month'] = df['time'].apply(lambda x: str(x)[4:6])
    df['day'] = df['time'].apply(lambda x: str(x)[6:8])
    df['hour'] = df['time'].apply(lambda x: str(x)[8:10])
    df['minute'] = '00' # minute을 넣어주지 않으면 datetime이 완성이 안되니, 00으로 넣어줍니다.
    
    df['time'] = pd.to_datetime(df.year + df.month + df.day + df.hour + df.minute)
    
    return df

In [18]:
train_p = make_datetime(train_p)
train_q = make_datetime(train_q)
test_q = make_datetime(test_q)
train_e = make_datetime(train_e)
test_e = make_datetime(test_e)

In [19]:
# groupby 연산에서 왜 문제가 생기나 했더니 category로 되어 있어서였습니다.

train_e['errtype'] = train_e.errtype.astype('object')
test_e['errtype'] = test_e.errtype.astype('object')

train_e['errcode'] = train_e.errcode.astype('object')
test_e['errcode'] = test_e.errcode.astype('object')

In [20]:
# fwver도 object로 잡아줍니다.

train_q.fwver = train_q.fwver.astype('object')
test_q.fwver = test_q.fwver.astype('object')

# EDA feature Collection 2

### errcode 마무리

In [21]:
temp = train_e[['errtype', 'errcode']].drop_duplicates()
count = {}

for i in sorted(temp.errtype.unique()):
    count[i] = (len(temp[temp.errtype == i]['errcode'].unique()))

In [22]:
err_type_user_counts = []
for i in sorted(train_e.errtype.unique()):
    err_type_user_counts.append(train_e[train_e.errtype == i].groupby('user_id').count().shape[0])

train_p['target'] = 1
temp = pd.merge(train_e, train_p, how='left', on=['user_id'])
temp2 = temp[temp.target == 1]

err_type_user_counts_origin = []
for i in sorted(temp2.errtype.unique()):
    err_type_user_counts_origin.append(temp2[temp2.errtype == i].groupby('user_id').count().shape[0])

In [23]:
etuc_1 = np.array(err_type_user_counts)
etuc_2 = np.array(err_type_user_counts_origin)

In [24]:
errcode_df = pd.DataFrame()
errcode_df['etuc_1'] = etuc_1
errcode_df['etuc_2'] = etuc_2
errcode_df['div'] = ((etuc_2 / etuc_1) * 100).round(2)
errcode_df['unique'] = count.values()

In [25]:
errcode_df = errcode_df.set_index([sorted(train_e.errtype.unique())])

In [26]:
errcode_df['perf'] = np.nan

In [27]:
errcode_df.loc[errcode_df.unique == 1, 'perf'] = 'pass'
errcode_df.loc[errcode_df.index == 31, 'perf'] = 'reject'
errcode_df.loc[errcode_df.index == 41, 'perf'] = 'reject'
errcode_df.loc[errcode_df.index == 17, 'perf'] = 'reject'
errcode_df.loc[errcode_df.index == 23, 'perf'] = 'adopt'
errcode_df.loc[errcode_df.index == 33, 'perf'] = 'adopt'
errcode_df.loc[errcode_df.index == 40, 'perf'] = 'reject'
errcode_df.loc[errcode_df.index == 14, 'perf'] = 'reject'
errcode_df.loc[errcode_df.index == 37, 'perf'] = 'reject'
errcode_df.loc[errcode_df.index == 7, 'perf'] = 'reject'
errcode_df.loc[errcode_df.index == 4, 'perf'] = 'reject'
errcode_df.loc[errcode_df.index == 6, 'perf'] = 'reject'
errcode_df.loc[errcode_df.index == 34, 'perf'] = 'adopt'
errcode_df.loc[errcode_df.index == 5, 'perf'] = 'reject'
errcode_df.loc[errcode_df.index == 42, 'perf'] = 'reject'
errcode_df.loc[errcode_df.index == 38, 'perf'] = 'reject'
errcode_df.loc[errcode_df.index == 32, 'perf'] = 'hold' # model 성능은 올라갔으나, 리더보드 하락
errcode_df.loc[errcode_df.index == 3, 'perf'] = 'hold'

In [28]:
errcode_df[errcode_df.perf.isnull()]

    etuc_1  etuc_2    div  unique perf
1      950     242  25.47       8  NaN
2      390     168  43.08       2  NaN
8       64      13  20.31       3  NaN
9       63      38  60.32       9  NaN
25     420     360  85.71       9  NaN
30     375     260  69.33       5  NaN
39     766     405  52.87       2  NaN

In [364]:
errcode_df.sort_values('etuc_1')

    etuc_1  etuc_2    div  unique    perf
9       63      38  60.32       9     NaN
8       64      13  20.31       3     NaN
30     375     260  69.33       5     NaN
21     381     316  82.94       1    pass
2      390     168  43.08       2     NaN
19     419     346  82.58       1    pass
25     420     360  85.71       9     NaN
39     766     405  52.87       2     NaN
1      950     242  25.47       8     NaN
20    1546    1333  86.22       1    pass
3     1679     465  27.70       3    hold
18    1768    1521  86.03       1    pass
38    1822     927  50.88    2653  reject
32    1933     927  47.96      55    hold
35    2039    1186  58.17       1    pass
27    2267     958  42.26       1    pass
28    2275     959  42.15       1    pass
10    2360    1134  48.05       1    pass
24    2519    1166  46.29       1    pass
13    3711    1667  44.92       1    pass
34    3733    1963  52.59       6   adopt
17    5747    2498  43.47       5  reject
41    6142    2596  42.27       1  reject
42    6382    2490  39.02       2  reject
6     6467    2662  41.16       2  reject
4     6881    2298  33.40       2  reject
7     7648    3093  40.44       2  reject
14    7891    3224  40.86       3  reject
37    8434    3259  38.64       2  reject
36    8435    3262  38.67       1    pass
23   10046    3920  39.02       8   adopt
22   10281    3975  38.66       1    pass
40   10462    4052  38.73       2  reject
5    11010    4028  36.58      65  reject
33   11074    4138  37.37       3   adopt
31   11091    4153  37.44       2  reject
26   13026    4632  35.56       1    pass
16   14431    4977  34.49       1    pass
15   14545    4978  34.22       1    pass
11   14767    4971  33.66       1    pass
12   14799    4974  33.61       1    pass

이 친구들은 도전하지 않겠습니다.

### Quality 다시 살펴보기

가설 세우기.

1. fwver별로 퀄리티 평균을 구해서 fwver별로 차이를 구해준다면. 제일 처음 것과 제일 마지막 것의 차이를 주는 것. 1개만 쓰면 0, 음수가 될 수도 있고, 양수가 될 수도 있고.
2. 단순히 q로그가 몇 번 있었는지를 기록했는데, 정지훈 선생의 가설 대로 0이 default 값이라면, 0이 아닌 값이 몇 번 일어났는가도 중요하지 않을까.
3.

#### quality log 살펴보기

In [29]:
for i in [0, 1, 2, 5, 6, 7, 8, 9, 10, 11, 12]:
    print(i,'번째 nunique: ' ,train_q['quality_{}'.format(i)].nunique())

0 번째 nunique:  754
1 번째 nunique:  31
2 번째 nunique:  799
5 번째 nunique:  4745
6 번째 nunique:  549
7 번째 nunique:  884
8 번째 nunique:  42
9 번째 nunique:  523
10 번째 nunique:  4200
11 번째 nunique:  12
12 번째 nunique:  14

In [30]:
for i in [0, 1, 2, 5, 6, 7, 8, 9, 10, 11, 12]:
    print(i,'번째 nunique: ' ,test_q['quality_{}'.format(i)].nunique())

0 번째 nunique:  541
1 번째 nunique:  35
2 번째 nunique:  597
5 번째 nunique:  3995
6 번째 nunique:  528
7 번째 nunique:  839
8 번째 nunique:  44
9 번째 nunique:  431
10 번째 nunique:  3515
11 번째 nunique:  13
12 번째 nunique:  17

In [31]:
for i in [0, 1, 2, 5, 6, 7, 8, 9, 10, 11, 12]:
    print(train_q['quality_{}'.format(i)].value_counts().head(10))

 0.0    542790
-2.0    144432
-1.0    130828
 1.0      2097
 2.0      1252
 3.0       518
 4.0       410
 5.0       385
 6.0       358
 7.0       314
Name: quality_0, dtype: int64
 0    670270
-1    153649
 1      2567
 2      1140
 3       391
 4       202
 5       134
 6        71
 7        50
 8        35
Name: quality_1, dtype: int64
 0.0    632469
-1.0    144392
-2.0     40113
 1.0      2937
 2.0      1073
 3.0       580
 4.0       455
 5.0       427
 6.0       386
 7.0       337
Name: quality_2, dtype: int64
 0.0    428096
-1.0    153354
 1.0     56171
 2.0     35978
 3.0     21596
 4.0     11204
 5.0      8536
 6.0      6836
 7.0      5506
 8.0      4495
Name: quality_5, dtype: int64
 0      662217
-1      153531
 600      1852
 1        1347
 5         644
 2         603
 3         475
 6         445
 4         408
 10        320
Name: quality_6, dtype: int64
0.0     757788
1.0       6768
2.0       3648
5.0       3456
6.0       2688
3.0       2568
4.0       2124
10.0      1632
11.0      1452
7.0       1164
Name: quality_7, dtype: int64
0.0    787812
1.0     19104
2.0      8832
3.0      4020
4.0      2592
5.0      1692
6.0      1116
7.0       744
8.0       480
9.0       384
Name: quality_8, dtype: int64
0.0    796284
1.0      9024
2.0      2772
3.0      1800
4.0      1416
6.0      1176
5.0      1152
7.0       564
8.0       420
9.0       396
Name: quality_9, dtype: int64
3.0    99828
2.0    81732
0.0    59028
1.0    58152
4.0    54948
5.0    40812
6.0    32220
7.0    24036
8.0    19212
9.0    15756
Name: quality_10, dtype: int64
 0     672229
-1     153678
 1       2428
 2        203
 3         50
 4         19
 5          8
 6          5
 14         1
 9          1
Name: quality_11, dtype: int64
0     801156
1      20880
2       4524
3       1320
4        312
5        192
6        108
8         48
7         24
14        12
Name: quality_12, dtype: int64

In [32]:
for i in [0, 1, 2, 5, 6, 7, 8, 9, 10, 11, 12]:
    print(test_q['quality_{}'.format(i)].value_counts().head(10))

 0.0    505710
-1.0    127001
-2.0    106584
 1.0      2319
 2.0      1567
 3.0       739
 4.0       454
 5.0       290
 6.0       212
 8.0       158
Name: quality_0, dtype: int64
 0.0    601265
-1.0    141905
 1.0      2573
 2.0      1119
 3.0       451
 4.0       201
 5.0       130
 6.0       101
 7.0        58
 8.0        37
Name: quality_1, dtype: int64
 0.0    578838
-1.0    136864
-2.0     21115
 1.0      3690
 2.0      1629
 3.0       962
 4.0       625
 5.0       391
 6.0       295
 7.0       203
Name: quality_2, dtype: int64
 0.0    399032
-1.0    141788
 1.0     52431
 2.0     33814
 3.0     20164
 4.0     10797
 5.0      8320
 6.0      6500
 7.0      4821
 8.0      3983
Name: quality_5, dtype: int64
 0      594594
-1      141866
 600      1848
 1        1206
 5         548
 2         521
 3         418
 4         400
 6         393
 10        309
Name: quality_6, dtype: int64
0.0     682584
1.0       6408
5.0       3612
2.0       2988
6.0       2400
3.0       2220
4.0       2100
10.0      1644
11.0      1548
7.0       1224
Name: quality_7, dtype: int64
0.0    707868
1.0     18504
2.0      8304
3.0      4116
4.0      2424
5.0      1668
6.0      1188
7.0       792
8.0       480
9.0       384
Name: quality_8, dtype: int64
0.0    715716
1.0      8772
2.0      3132
3.0      1920
4.0      1344
5.0      1248
6.0       744
7.0       696
8.0       684
9.0       564
Name: quality_9, dtype: int64
3.0    98688
2.0    78984
1.0    58608
4.0    55608
0.0    45072
5.0    41208
6.0    32460
7.0    22056
8.0    17952
9.0    15588
Name: quality_10, dtype: int64
 0     603983
-1     141917
 1       1816
 2        169
 3         45
 4         20
 5         10
 6          4
 12         2
 9          2
Name: quality_11, dtype: int64
0    727188
1     16140
2      2976
3       828
4       264
6       168
5       132
8        72
9        48
7        36
Name: quality_12, dtype: int64

7, 8, 9, 10, 12 는 음수 값이 없습니다. 0, 1, 2, 5, 6, 11 은 음수 값이 존재합니다.

In [33]:
train_q_some = train_q[['user_id', 'quality_7', 'quality_8', 'quality_9', 'quality_10', 'quality_12']]
test_q_some = test_q[['user_id', 'quality_7', 'quality_8', 'quality_9', 'quality_10', 'quality_12']]

In [34]:
train_q_some

        user_id  quality_7  quality_8  quality_9  quality_10  quality_12
0         10000        0.0        0.0        0.0         4.0           0
1         10000        0.0        0.0        0.0         4.0           0
2         10000        0.0        0.0        0.0         4.0           0
3         10000        0.0        0.0        0.0         4.0           0
4         10000        0.0        0.0        0.0         4.0           0
...         ...        ...        ...        ...         ...         ...
828619    24997        0.0        0.0        0.0        17.0           0
828620    24997        0.0        0.0        0.0        17.0           0
828621    24997        0.0        0.0        0.0        17.0           0
828622    24997        0.0        0.0        0.0        17.0           0
828623    24997        0.0        0.0        0.0        17.0           0

[828624 rows x 6 columns]

#### 몇 번이나 연속해서 quality가 기록되었는가?

In [111]:
temp = train_q.groupby('user_id').count()['time']

In [122]:
temp.loc[:] = np.nan

In [123]:
temp

user_id
10000   NaN
10002   NaN
10004   NaN
10005   NaN
10006   NaN
         ..
24990   NaN
24992   NaN
24993   NaN
24995   NaN
24997   NaN
Name: time, Length: 8281, dtype: float64

In [207]:
temp_train = train_q.groupby('user_id').count()['time']
user_quality_log_gap = {}
for user in train_q.user_id.unique():
    time = train_q[train_q.user_id == user].time.drop_duplicates().values
    time_sum = 0
    if len(time) < 1:
        pass
    else:
        for i in range(len(time) - 1):
            time_sum += time[i] - time[i+1]
            
        temp_train[user] = time_sum/60000000000
        
temp_train = temp_train.rename('time_gap')

In [208]:
temp_test = test_q.groupby('user_id').count()['time']
user_quality_log_gap = {}
for user in test_q.user_id.unique():
    time = test_q[test_q.user_id == user].time.drop_duplicates().values
    time_sum = 0
    if len(time) < 1:
        pass
    else:
        for i in range(len(time) - 1):
            time_sum += time[i] - time[i+1]
            
        temp_test[user] = time_sum/60000000000
        
temp_test = temp_test.rename('time_gap')

In [209]:
temp_train

user_id
10000    -2160
10002   -36960
10004    -2220
10005     -120
10006   -24840
         ...
24990   -18120
24992    -1440
24993   -42180
24995     -240
24997   -21840
Name: time_gap, Length: 8281, dtype: int64

In [210]:
temp_test

user_id
30000        0
30001   -13440
30002   -25320
30003   -12960
30004    -7200
         ...
44990   -28380
44993   -35700
44994        0
44996   -33840
44997   -32940
Name: time_gap, Length: 8268, dtype: int64

In [97]:
time = train_q[train_q.user_id == 10019].time.drop_duplicates().values

In [101]:
time[2]

numpy.datetime64('2020-11-04T21:00:00.000000000')

In [78]:
train_p[train_p.user_id == 10019]

      user_id                time  year month day hour minute  target
4158    10019 2020-11-24 11:00:00  2020    11  24   11     00       1

In [80]:
train_e[train_e.user_id == 10019].time.drop_duplicates()

23826   2020-11-01 06:00:00
23831   2020-11-01 10:00:00
23836   2020-11-01 11:00:00
23837   2020-11-01 18:00:00
23842   2020-11-02 06:00:00
                ...
24649   2020-11-29 18:00:00
24654   2020-11-30 07:00:00
24659   2020-11-30 10:00:00
24663   2020-11-30 12:00:00
24668   2020-11-30 18:00:00
Name: time, Length: 153, dtype: datetime64[ns]

In [240]:
train_q.time[0] + pd.Timedelta(hours=2) == train_q.time[12]

False

In [238]:
train_q.time[12]

Timestamp('2020-11-30 21:00:00')

In [268]:
train_origin_time = train_q[['user_id', 'time']].drop_duplicates()
time_continue = []

for i in range(train_origin_time.shape[0] - 1):
    if train_origin_time.user_id.iloc[i] == train_origin_time.user_id.iloc[i+1]:
        if train_origin_time.time.iloc[i] + pd.Timedelta(hours=2) == train_origin_time.time.iloc[i+1]:
            time_continue.append(1)
        else:
            time_continue.append(0)
    else:
        time_continue.append(0)
        
train_origin_time['t_continue'] = time_continue + [0]

train_qual_conti = train_origin_time.groupby(['user_id'])['t_continue'].sum()

In [269]:
test_origin_time = test_q[['user_id', 'time']].drop_duplicates()
time_continue = []

for i in range(test_origin_time.shape[0] - 1):
    if test_origin_time.user_id.iloc[i] == test_origin_time.user_id.iloc[i+1]:
        if test_origin_time.time.iloc[i] + pd.Timedelta(hours=2) == test_origin_time.time.iloc[i+1]:
            time_continue.append(1)
        else:
            time_continue.append(0)
    else:
        time_continue.append(0)
        
test_origin_time['t_continue'] = time_continue + [0]

test_qual_conti = test_origin_time.groupby(['user_id'])['t_continue'].sum()

In [270]:
train_qual_conti

user_id
10000    0
10002    1
10004    0
10005    1
10006    0
        ..
24990    0
24992    0
24993    0
24995    0
24997    0
Name: t_continue, Length: 8281, dtype: int64

In [271]:
test_qual_conti

user_id
30000    0
30001    0
30002    3
30003    1
30004    0
        ..
44990    0
44993    0
44994    0
44996    1
44997    0
Name: t_continue, Length: 8268, dtype: int64

#### quality 별로 몇 번이나 기록되었는가?

In [35]:
train_q_temp = train_q.copy()
test_q_temp = test_q.copy()

count를 위해서 0 값을 전부 nan으로 만들겠습니다.

In [36]:
for i in [0, 1, 2, 5, 6, 7, 8, 9, 10, 11, 12]:
    train_q_temp.loc[train_q_temp['quality_{}'.format(i)] == 0, 'quality_{}'.format(i)] = np.nan
    
for i in [0, 1, 2, 5, 6, 7, 8, 9, 10, 11, 12]:
    test_q_temp.loc[test_q_temp['quality_{}'.format(i)] == 0, 'quality_{}'.format(i)] = np.nan

In [37]:
train_q_temp.drop(['time', 'fwver', 'year', 'month', 'day', 'hour', 'minute'], axis=1, inplace=True)
test_q_temp.drop(['time', 'fwver', 'year', 'month', 'day', 'hour', 'minute'], axis=1, inplace=True)

In [38]:
train_qual_counts = train_q_temp.groupby('user_id').count()
test_qual_counts = test_q_temp.groupby('user_id').count()

In [39]:
train_qual_counts.columns = ['q_c_0', 'q_c_1', 'q_c_2', 'q_c_5', 'q_c_6',
                             'q_c_7', 'q_c_8', 'q_c_9', 'q_c_10', 'q_c_11', 'q_c_12']
test_qual_counts.columns = ['q_c_0', 'q_c_1', 'q_c_2', 'q_c_5', 'q_c_6',
                             'q_c_7', 'q_c_8', 'q_c_9', 'q_c_10', 'q_c_11', 'q_c_12']

리더보드는 올랐습니다. 아주 미세하게.

#### 0을 빼고 전부 1로 바꿔버리는 겁니다. 그리고 옆으로 스택해주는 것이죠. 몰라요 그냥 해볼래요.

In [290]:
train_q_temp = train_q.copy()
test_q_temp = test_q.copy()

In [291]:
train_q_temp.drop(['time', 'fwver', 'year', 'month', 'day', 'hour', 'minute'], axis=1, inplace=True)
test_q_temp.drop(['time', 'fwver', 'year', 'month', 'day', 'hour', 'minute'], axis=1, inplace=True)

In [301]:
qual_columns = ['quality_0', 'quality_1', 'quality_2', 'quality_5', 'quality_6', 'quality_7', 'quality_8', 'quality_9', 'quality_10','quality_11', 'quality_12']

for col in qual_columns:
    train_q_temp[col] = train_q_temp[col].apply(lambda x: 1 if x != 0 else x)
    
for col in qual_columns:
    test_q_temp[col] = test_q_temp[col].apply(lambda x: 1 if x != 0 else x)

In [316]:
train_qual_onehot = train_q_temp.groupby('user_id').max()
test_qual_onehot = test_q_temp.groupby('user_id').max()

In [317]:
new_columns = ['q_o_h_0', 'q_o_h_1', 'q_o_h_2', 'q_o_h_5', 'q_o_h_6', 'q_o_h_7', 'q_o_h_8', 'q_o_h_9', 'q_o_h_10','q_o_h_11', 'q_o_h_12']

train_qual_onehot.columns = new_columns
test_qual_onehot.columns = new_columns

#### fwver별로 quality 살펴보기

In [181]:
train_b_p[train_b_p.user_id == 10229]

     user_id  target
229    10229       0

In [288]:
train_q

,time,user_id,fwver,quality_0,quality_1,quality_2,quality_5,quality_6,quality_7,quality_8,quality_9,quality_10,quality_11,quality_12,year,month,day,hour,minute
0,2020-11-29 09:00:00,10000,05.15.2138,0.0,0,0.0,0.0,0,0.0,0.0,0.0,4.0,0,0,2020,11,29,09,00
1,2020-11-29 09:00:00,10000,05.15.2138,0.0,0,0.0,0.0,0,0.0,0.0,0.0,4.0,0,0,2020,11,29,09,00
2,2020-11-29 09:00:00,10000,05.15.2138,0.0,0,0.0,0.0,0,0.0,0.0,0.0,4.0,0,0,2020,11,29,09,00
3,2020-11-29 09:00:00,10000,05.15.2138,0.0,0,0.0,0.0,0,0.0,0.0,0.0,4.0,0,0,2020,11,29,09,00
4,2020-11-29 09:00:00,10000,05.15.2138,0.0,0,0.0,0.0,0,0.0,0.0,0.0,4.0,0,0,2020,11,29,09,00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
828619,2020-11-24 03:00:00,24997,04.22.1778,0.0,0,0.0,1.0,0,0.0,0.0,0.0,17.0,0,0,2020,11,24,03,00
828620,2020-11-24 03:00:00,24997,04.22.1778,0.0,0,0.0,0.0,0,0.0,0.0,0.0,17.0,0,0,2020,11,24,03,00
828621,2020-11-24 03:00:00,24997,04.22.1778,0.0,0,0.0,3.0,0,0.0,0.0,0.0,17.0,0,0,2020,11,24,03,00
828622,2020-11-24 03:00:00,24997,04.22.1778,0.0,0,0.0,0.0,0,0.0,0.0,0.0,17.0,0,0,2020,11,24,03,00
828623,2020-11-24 03:00:00,24997,04.22.1778,0.0,0,0.0,9.0,0,0.0,0.0,0.0,17.0,0,0,2020,11,24,03,00

In [287]:
train_q.groupby(['user_id', 'fwver']).mean().reset_index()[100:200]

,user_id,fwver,quality_0,quality_1,quality_2,quality_5,quality_6,quality_7,quality_8,quality_9,quality_10,quality_11,quality_12
100,10152,04.16.3553,0.000000,0.041667,0.000000,4.250000,0.000000,0.000000,0.500000,0.000000,51.000000,0.000000,0.000000
101,10153,04.33.1261,-0.166667,-0.166667,-0.166667,0.083333,-0.166667,0.000000,0.000000,0.000000,3.000000,-0.166667,0.000000
102,10154,04.33.1185,-0.333333,-0.333333,-0.333333,-0.083333,-0.333333,0.000000,0.000000,0.000000,3.000000,-0.333333,0.000000
103,10154,04.33.1261,-0.416667,-0.416667,-0.416667,23.041666,-0.416667,0.000000,0.000000,0.000000,281.500000,-0.416667,0.000000
104,10158,04.16.3553,0.000000,0.000000,0.000000,0.416667,0.000000,0.000000,0.000000,0.000000,5.000000,0.000000,0.000000
105,10160,04.16.3553,0.000000,0.000000,0.000000,0.250000,0.000000,0.000000,0.000000,0.000000,3.000000,0.000000,0.000000
106,10161,04.16.3553,-0.500000,-0.500000,-0.500000,-0.166667,-0.500000,0.000000,0.000000,0.000000,4.000000,-0.500000,0.000000
107,10163,04.22.1750,0.000000,0.000000,0.000000,0.567901,0.000000,0.000000,0.000000,0.000000,6.814815,0.000000,0.000000
108,10163,04.22.1778,-0.229167,-0.229167,-0.229167,0.208333,-0.229167,0.000000,0.000000,0.000000,5.250000,-0.229167,0.000000
109,10165,04.16.3553,-0.305556,-0.277778,-0.305556,0.500000,-0.305556,0.000000,0.333333,0.000000,9.666667,-0.305556,0.000000
110,10166,04.33.1185,-0.125000,-0.125000,-0.125000,0.125000,-0.125000,0.000000,0.000000,0.000000,3.000000,-0.125000,0.000000
111,10166,04.33.1261,-0.208333,-0.208333,-0.208333,137.902771,-0.166667,0.500000,0.000000,0.000000,1657.333374,-0.208333,0.000000
112,10167,03.11.1167,-2.000000,-0.267628,-0.275641,7.028846,-0.275641,0.000000,0.096154,0.000000,87.653847,-0.232372,0.519231
113,10168,03.11.1167,-2.000000,0.000000,0.000000,0.083333,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000
114,10171,03.11.1167,-2.000000,0.000000,0.000000,2.505952,0.000000,0.000000,0.000000,0.000000,30.071428,0.000000,0.000000
115,10173,04.16.3553,0.000000,0.000000,0.000000,0.208333,0.000000,0.000000,0.000000,0.000000,2.500000,0.000000,0.000000
116,10173,04.33.1261,-0.083333,-0.062500,-0.083333,0.625000,2.083333,26.000000,0.250000,0.000000,8.500000,-0.083333,0.000000
117,10174,04.33.1185,-0.416667,-0.416667,-0.416667,-0.083333,-0.416667,0.000000,0.000000,0.000000,4.000000,-0.416667,0.000000
118,10174,04.33.1261,-0.041667,-0.041667,-0.041667,0.041667,14.833333,178.500000,0.000000,0.000000,1.000000,-0.041667,0.000000
119,10175,04.16.3553,0.000000,0.000000,0.000000,213.375000,0.000000,0.000000,0.000000,0.000000,2560.500000,0.000000,0.000000
120,10178,04.22.1750,-0.250000,-0.250000,-0.250000,157.766663,-0.250000,0.000000,0.000000,0.000000,1896.199951,-0.250000,0.000000
121,10184,05.15.2138,-0.333333,-0.333333,-0.333333,0.541667,-0.333333,0.000000,0.000000,0.000000,10.500000,-0.333333,0.000000
122,10187,04.16.3553,-0.166667,-0.166667,-0.166667,0.291667,-0.166667,0.000000,0.000000,0.000000,5.500000,-0.166667,0.000000
123,10188,04.16.3553,-0.083333,-0.083333,-0.083333,0.166667,-0.083333,0.000000,0.000000,0.000000,3.000000,-0.083333,0.000000
124,10189,04.22.1750,-0.375000,-0.375000,-0.375000,-0.125000,-0.375000,0.000000,0.000000,0.000000,3.000000,-0.375000,0.000000
125,10191,05.15.2138,0.000000,0.000000,0.000000,0.250000,8.750000,105.000000,0.000000,0.000000,3.000000,0.000000,0.000000
126,10192,04.33.1261,-0.333333,-0.333333,-0.333333,0.250000,-0.333333,0.000000,0.000000,0.000000,7.000000,-0.333333,0.000000
127,10193,05.15.2138,-0.125000,-0.208333,-0.166667,-0.041667,-0.208333,0.000000,0.000000,0.500000,2.000000,-0.208333,0.000000
128,10194,04.16.3553,-0.083333,-0.083333,-0.083333,0.183333,-0.016667,0.800000,0.000000,0.000000,3.200000,-0.083333,0.000000
129,10195,05.15.2138,-0.093434,0.068182,-0.098485,-0.068182,0.093434,2.424242,2.121212,0.121212,0.484848,-0.108586,0.000000
130,10197,04.16.3553,-0.166667,-0.166667,-0.166667,0.250000,-0.166667,0.000000,0.000000,0.000000,5.000000,-0.166667,0.000000
131,10198,04.33.1185,0.000000,0.000000,0.000000,0.583333,0.000000,0.000000,0.000000,0.000000,7.000000,0.000000,0.000000
132,10198,04.33.1261,0.000000,0.000000,0.000000,0.166667,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000
133,10199,04.22.1778,-0.250000,-0.250000,-0.250000,0.000000,-0.250000,0.000000,0.000000,0.000000,3.000000,-0.250000,0.000000
134,10201,04.22.1750,-0.027778,-0.027778,-0.027778,481.111115,-0.027778,0.000000,0.000000,0.000000,5773.666504,-0.027778,0.000000
135,10203,05.15.2138,-0.250000,-0.250000,-0.250000,-0.041667,-0.166667,1.000000,0.000000,0.000000,2.500000,-0.250000,0.000000
136,10205,05.15.2138,-0.111111,-0.111111,-0.111111,0.138889,-0.083333,0.333333,0.000000,0.000000,3.000000,-0.111111,0.000000
137,10206,03.11.1167,-2.000000,-0.183333,-0.183333,-0.066667,-0.183333,0.000000,0.000000,0.000000,1.400000,-0.183333,0.000000
138,10207,03.11.1167,-2.000000,-0.150000,-0.150000,0.200000,-0.150000,0.000000,0.000000,0.000000,4.200000,-0.150000,0.000000
139,10208,04.22.1750,0.000000,0.000000,0.000000,0.375000,0.000000,0.000000,0.000000,0.000000,4.500000,0.000000,0.000000
140,10209,04.16.3553,-0.083333,-0.055556,-0.083333,0.277778,-0.083333,0.000000,0.333333,0.000000,4.333333,-0.083333,0.000000
141,10210,04.33.1185,0.000000,0.000000,0.000000,0.291667,0.000000,0.000000,0.000000,0.000000,3.500000,0.000000,0.000000
142,10210,04.33.1261,-0.222222,-0.222222,-0.222222,0.027778,-0.222222,0.000000,0.000000,0.000000,3.000000,-0.222222,0.000000
143,10213,04.22.1750,-0.011905,-0.011905,-0.011905,0.452381,-0.011905,0.000000,0.000000,0.000000,5.571429,-0.011905,0.000000
144,10213,04.22.1778,-0.055556,-0.055556,-0.055556,0.194444,-0.055556,0.000000,0.000000,0.000000,3.000000,-0.055556,0.000000
145,10214,04.16.3553,-0.166667,-0.166667,-0.166667,0.000000,-0.166667,0.000000,0.000000,0.000000,2.000000,-0.166667,0.000000
146,10215,04.16.3553,-0.416667,-0.416667,-0.416667,-0.166667,-0.416667,0.000000,0.000000,0.000000,3.000000,-0.416667,0.000000
147,10217,03.11.1167,-2.000000,-0.232639,-0.267361,-0.256944,-0.267361,0.000000,0.416667,0.000000,0.125000,-0.197917,0.833333
148,10218,04.22.1750,-0.166667,-0.041667,-0.166667,-0.041667,-0.166667,0.000000,1.500000,0.000000,1.500000,-0.166667,0.000000
149,10218,04.22.1778,-0.583333,-0.583333,-0.583333,-0.333333,-0.583333,0.000000,0.000000,0.000000,3.000000,-0.583333,0.000000
150,10219,04.33.1185,-0.305556,-0.305556,-0.305556,-0.027778,-0.305556,0.000000,0.000000,0.000000,3.333333,-0.305556,0.000000
151,10219,04.33.1261,-0.523810,-0.523810,-0.523810,0.023810,-0.523810,0.000000,0.000000,0.000000,6.571429,-0.523810,0.000000
152,10222,04.33.1261,0.000000,0.000000,0.000000,0.333333,0.000000,0.000000,0.000000,0.000000,4.000000,0.000000,0.000000
153,10226,04.22.1750,0.000000,0.000000,0.000000,0.083333,6.833333,82.000000,0.000000,0.000000,1.000000,0.000000,0.000000
154,10227,04.33.1185,-0.208333,-0.208333,-0.208333,0.208333,-0.208333,0.000000,0.000000,0.000000,5.000000,-0.208333,0.000000
155,10229,04.33.1185,-0.194444,-0.194444,-0.194444,0.111111,-0.194444,0.000000,0.000000,0.000000,3.666667,-0.194444,0.000000
156,10229,04.33.1261,-0.178571,-0.130952,-0.178571,-0.011905,0.845238,12.285714,0.571429,0.000000,2.000000,-0.178571,0.000000
157,10232,04.16.3553,-0.458333,-0.458333,-0.458333,-0.166667,3.375000,46.000000,0.000000,0.000000,3.500000,-0.458333,0.000000
158,10234,04.22.1750,-0.341667,-0.341667,-0.341667,-0.041667,-0.341667,0.000000,0.000000,0.000000,3.600000,-0.341667,0.000000
159,10234,04.22.1778,-0.472222,-0.472222,-0.472222,-0.111111,-0.472222,0.000000,0.000000,0.000000,4.333333,-0.472222,0.000000
160,10235,04.22.1778,0.000000,0.000000,0.000000,0.166667,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000
161,10236,04.16.3553,-0.205556,-0.200000,-0.205556,12.755555,0.622222,9.933333,0.066667,0.000000,155.533340,-0.205556,0.000000
162,10237,04.33.1185,-0.333333,-0.333333,-0.333333,-0.083333,-0.333333,0.000000,0.000000,0.000000,3.000000,-0.333333,0.000000
163,10238,05.15.2138,0.000000,0.000000,0.000000,0.166667,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000
164,10239,04.16.3553,-0.058642,-0.058642,-0.058642,2.259259,4.888889,59.370369,0.000000,0.000000,27.814816,-0.058642,0.000000
165,10241,05.15.2138,-0.416667,-0.416667,-0.416667,-0.166667,-0.416667,0.000000,0.000000,0.000000,3.000000,-0.416667,0.000000
166,10242,04.33.1261,0.000000,0.000000,0.000000,0.000000,106.666667,1280.000000,0.000000,0.000000,0.000000,0.000000,0.000000
167,10243,03.11.1167,-2.000000,-0.583333,-0.583333,-0.416667,-0.583333,0.000000,0.000000,0.000000,2.000000,-0.583333,0.000000
168,10246,04.33.1185,-0.458333,-0.208333,-0.458333,-0.458333,8.562500,108.250000,3.000000,0.000000,0.000000,-0.458333,0.000000
169,10246,04.33.1261,-0.170139,0.402778,-0.170139,-0.163194,-0.170139,0.000000,6.875000,0.000000,0.083333,-0.170139,0.000000
170,10249,04.16.3553,-0.666667,-0.666667,-0.666667,-0.222222,-0.666667,0.000000,0.000000,0.000000,5.333333,-0.666667,0.000000
171,10251,05.15.2138,0.152778,-0.041667,0.152778,0.802778,-0.041667,0.000000,0.000000,2.333333,10.133333,-0.041667,0.000000
172,10252,04.16.3553,0.000000,0.000000,0.000000,0.250000,0.000000,0.000000,0.000000,0.000000,3.000000,0.000000,0.000000
173,10253,04.22.1750,0.000000,0.000000,0.000000,0.916667,0.000000,0.000000,0.000000,0.000000,11.000000,0.000000,0.000000
174,10255,04.33.1185,0.000000,0.000000,0.000000,0.750000,0.000000,0.000000,0.000000,0.000000,9.000000,0.000000,0.000000
175,10256,04.22.1778,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,12.000000,0.000000,0.000000
176,10259,04.33.1185,-0.041667,0.041667,-0.041667,0.000000,4.500000,54.500000,1.000000,0.000000,0.500000,-0.041667,0.000000
177,10262,04.16.3553,-0.236111,-0.236111,-0.236111,0.097222,-0.236111,0.000000,0.000000,0.000000,4.000000,-0.236111,0.000000
178,10263,03.11.1167,-2.000000,-0.125000,-0.125000,0.062500,-0.125000,0.000000,0.000000,0.000000,2.250000,-0.125000,0.000000
179,10264,04.33.1261,0.000000,0.000000,0.000000,0.166667,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000
180,10265,03.11.1167,-2.000000,-0.025000,454.240631,67.740623,0.736458,9.162500,0.025000,5451.212402,813.212524,-0.021875,0.062500
181,10266,05.15.2138,-0.066667,-0.066667,-0.066667,140.233337,-0.066667,0.000000,0.000000,0.000000,1683.599976,-0.066667,0.000000
182,10268,03.11.1167,-2.000000,0.000000,0.000000,0.000000,0.083333,1.000000,0.000000,0.000000,0.000000,0.083333,1.000000
183,10270,04.22.1750,-0.416667,-0.416667,-0.416667,0.000000,-0.416667,0.000000,0.000000,0.000000,5.000000,-0.416667,0.000000
184,10271,04.22.1750,-0.208333,-0.208333,-0.208333,0.000000,2.583333,33.500000,0.000000,0.000000,2.500000,-0.208333,0.000000
185,10273,05.15.2138,-0.277778,-0.250000,-0.277778,0.055556,-0.277778,0.000000,0.333333,0.000000,4.000000,-0.277778,0.000000
186,10275,04.22.1750,0.000000,0.000000,0.000000,0.333333,0.000000,0.000000,0.000000,0.000000,4.000000,0.000000,0.000000
187,10276,04.22.1750,0.000000,0.000000,0.000000,0.166667,10.750000,129.000000,0.000000,0.000000,2.000000,0.000000,0.000000
188,10277,04.16.3553,-0.166667,-0.166667,-0.166667,124.694443,-0.138889,0.333333,0.000000,0.000000,1498.333374,-0.166667,0.000000
189,10278,04.16.3553,-0.750000,-0.750000,-0.750000,-0.583333,-0.750000,0.000000,0.000000,0.000000,2.000000,-0.750000,0.000000
190,10279,05.15.2138,-0.083333,-0.083333,-0.083333,1.000000,4.166667,51.000000,0.000000,0.000000,13.000000,-0.083333,0.000000
191,10280,04.22.1750,-0.750000,-0.750000,-0.750000,-0.416667,-0.750000,0.000000,0.000000,0.000000,4.000000,-0.750000,0.000000
192,10281,04.33.1185,-0.337963,-0.337963,-0.337963,23.768518,-0.337963,0.000000,0.000000,0.000000,289.277771,-0.337963,0.000000
193,10281,04.33.1261,-0.416667,-0.416667,-0.416667,-0.166667,-0.416667,0.000000,0.000000,0.000000,3.000000,-0.416667,0.000000
194,10282,05.15.2138,-0.104167,-0.104167,-0.104167,0.062500,-0.104167,0.000000,0.000000,0.000000,2.000000,-0.104167,0.000000
195,10285,05.15.2138,-0.416667,-0.416667,-0.416667,0.250000,-0.416667,0.000000,0.000000,0.000000,8.000000,-0.416667,0.000000
196,10287,04.22.1750,0.000000,0.000000,0.000000,0.250000,0.000000,0.000000,0.000000,0.000000,3.000000,0.000000,0.000000
197,10288,05.15.2138,-0.500000,-0.500000,-0.500000,-0.250000,-0.500000,0.000000,0.000000,0.000000,3.000000,-0.500000,0.000000
198,10289,05.15.2138,-0.013889,-0.013889,-0.013889,0.319444,1.611111,19.500000,0.000000,0.000000,4.000000,-0.013889,0.000000
199,10290,04.33.1185,-0.291667,-0.291667,-0.291667,0.125000,-0.291667,0.000000,0.000000,0.000000,5.000000,-0.291667,0.000000

In [328]:
train_q.groupby('user_id').mean()

,quality_0,quality_1,quality_2,quality_5,quality_6,quality_7,quality_8,quality_9,quality_10,quality_11,quality_12
user_id,,,,,,,,,,,
10000,0.000000,0.000000,0.000000,0.500000,0.000000,0.000000,0.0,0.000,6.000000,0.000000,0.0
10002,0.000000,-0.020833,-0.010417,0.302083,0.458333,5.750000,0.0,0.125,3.875000,-0.020833,0.0
10004,-0.083333,-0.083333,-0.083333,0.083333,3.541667,43.500000,0.0,0.000,2.000000,-0.083333,0.0
10005,-0.416667,-0.416667,-0.416667,0.000000,1.083333,18.000000,0.0,0.000,5.000000,-0.416667,0.0
10006,0.000000,0.000000,0.000000,0.333333,0.111111,1.333333,0.0,0.000,4.000000,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...
24990,-2.000000,-0.333333,-0.333333,-0.250000,-0.333333,0.000000,0.0,0.000,1.000000,-0.333333,0.0
24992,-0.333333,-0.333333,-0.333333,0.194444,-0.333333,0.000000,0.0,0.000,6.333333,-0.333333,0.0
24993,-0.291667,-0.291667,-0.291667,0.041667,-0.291667,0.000000,0.0,0.000,4.000000,-0.291667,0.0
24995,-0.416667,-0.416667,-0.416667,-0.208333,-0.416667,0.000000,0.0,0.000,2.500000,-0.416667,0.0
24997,-0.166667,-0.166667,-0.166667,0.625000,-0.166667,0.000000,0.0,0.000,9.500000,-0.166667,0.0

In [329]:
train_q.groupby('user_id').std()

,quality_0,quality_1,quality_2,quality_5,quality_6,quality_7,quality_8,quality_9,quality_10,quality_11,quality_12
user_id,,,,,,,,,,,
10000,0.000000,0.000000,0.000000,1.793709,0.000000,0.000000,0.0,0.000000,2.043016,0.000000,0.0
10002,0.251312,0.143576,0.177396,1.037404,4.495417,14.547924,0.0,0.332455,2.327185,0.143576,0.0
10004,0.282330,0.282330,0.282330,0.583592,17.778784,44.435591,0.0,0.000000,1.021508,0.282330,0.0
10005,0.503610,0.503610,0.503610,1.179536,5.867498,18.387141,0.0,0.000000,1.021508,0.503610,0.0
10006,0.000000,0.000000,0.000000,1.121224,0.666667,1.912366,0.0,0.000000,0.000000,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...
24990,0.000000,0.481543,0.481543,0.607919,0.481543,0.000000,0.0,0.000000,0.000000,0.481543,0.0
24992,0.478091,0.478091,0.478091,1.879505,0.478091,0.000000,0.0,0.000000,2.908117,0.478091,0.0
24993,0.464306,0.464306,0.464306,1.334465,0.464306,0.000000,0.0,0.000000,1.021508,0.464306,0.0
24995,0.503610,0.503610,0.503610,0.977093,0.503610,0.000000,0.0,0.000000,0.510754,0.503610,0.0
24997,0.380693,0.380693,0.380693,2.060234,0.380693,0.000000,0.0,0.000000,7.661309,0.380693,0.0

In [332]:
train_qual_mean = train_q.groupby(['user_id']).mean()
test_qual_mean = test_q.groupby(['user_id']).mean()

new_columns = ['q_mean_0', 'q_mean_1', 'q_mean_2', 'q_mean_5', 'q_mean_6', 'q_mean_7', 'q_mean_8', 'q_mean_9', 'q_mean_10','q_mean_11', 'q_mean_12']

train_qual_mean.columns = new_columns
test_qual_mean.columns = new_columns

## q에 한 번도 등장하지 않은 user

In [455]:
origin_q_train_user = list(train_q.user_id.unique())
train_all_user = list(np.arange(10000, 25000, 1))

In [456]:
origin_q_test_user = list(test_q.user_id.unique())
test_all_user = list(np.arange(30000, 49999, 1))

In [458]:
X_q = X.loc[origin_q_train_user,:]
y_q = y.loc[origin_q_test_user, :]

In [483]:
X_nq = X.drop(origin_q_train_user, axis=0)
y_nq = y.drop(origin_q_test_user, axis=0)

# Survived Features from Feature Collection 1

### from Error_log

#### 보유한 model의 개수

In [484]:
train_model_count = train_e[['user_id', 'model_nm']].drop_duplicates().groupby('user_id').count()
test_model_count = test_e[['user_id', 'model_nm']].drop_duplicates().groupby('user_id').count()

#### 보유한 fwver 의 개수

In [485]:
train_fwver_count = train_e[['user_id', 'fwver']].drop_duplicates().groupby('user_id').count()
test_fwver_count = test_e[['user_id', 'fwver']].drop_duplicates().groupby('user_id').count()

#### 경험한 error 의 총 개수

In [486]:
train_err_count = train_e.groupby('user_id')['errcode'].count()
test_err_count = test_e.groupby('user_id')['errcode'].count()

#### 경험한 각 errtype의 values의 개수

In [487]:
# 33호
train_errcode_33 = train_e[train_e.errtype == 33][['user_id', 'errcode', 'hour']].groupby(['user_id', 'errcode']).count().unstack().fillna(0)
test_errcode_33 = test_e[test_e.errtype == 33][['user_id', 'errcode', 'hour']].groupby(['user_id', 'errcode']).count().unstack().fillna(0)

train_errcode_33.columns = ['err_33_1', 'err_33_2', 'err_33_3']
test_errcode_33.columns = ['err_33_1', 'err_33_2', 'err_33_3']

In [488]:
# 23호
train_errcode_23 = train_e[train_e.errtype == 23][['user_id', 'errcode', 'hour']].groupby(['user_id', 'errcode']).count().unstack().fillna(0)
test_errcode_23 = test_e[test_e.errtype == 23][['user_id', 'errcode', 'hour']].groupby(['user_id', 'errcode']).count().unstack().fillna(0)

train_errcode_23.columns = ['UNKNOWN', 'ACTIVE', 'connLMP', 'connESTA', 'connTO', 'connLOCAL', 'STANDBY', 'TERMINATE']
test_errcode_23.columns = ['UNKNOWN', 'ACTIVE', 'connLMP', 'connESTA', 'connTO', 'connLOCAL', 'STANDBY', 'TERMINATE']

In [489]:
# 34호
train_errcode_34 = train_e[train_e.errtype == 34][['user_id', 'errcode', 'hour']].groupby(['user_id', 'errcode']).count().unstack().fillna(0)
test_errcode_34 = test_e[test_e.errtype == 34][['user_id', 'errcode', 'hour']].groupby(['user_id', 'errcode']).count().unstack().fillna(0)

train_errcode_34.columns = ['err_34_1', 'err_34_2', 'err_34_3', 'err_34_4', 'err_34_5', 'err_34_6']
test_errcode_34.columns = ['err_34_1', 'err_34_2', 'err_34_3', 'err_34_4', 'err_34_5', 'err_34_6']

### from Quality_log

#### 각 quality의 표준편차

In [490]:
train_qual_std = train_q.groupby(['user_id']).std()
test_qual_std = test_q.groupby(['user_id']).std()

new_columns = ['q_std_0', 'q_std_1', 'q_std_2', 'q_std_5', 'q_std_6', 'q_std_7', 'q_std_8', 'q_std_9', 'q_std_10','q_std_11', 'q_std_12']

train_qual_std.columns = new_columns
test_qual_std.columns = new_columns

#### 기록한 quality log의 개수(12개당 1번)

In [491]:
train_qual_log = train_q.groupby('user_id')['time'].count()/12
test_qual_log = test_q.groupby('user_id')['time'].count()/12

#### quality당 순수 개수

In [492]:
# 값을 만들기 위해 새로운 df를 받아옵니다.
train_q_temp = train_q.copy()
test_q_temp = test_q.copy()

# 0 값을 전부 nan 값으로 바꿔줍니다.
for i in [0, 1, 2, 5, 6, 7, 8, 9, 10, 11, 12]:
    train_q_temp.loc[train_q_temp['quality_{}'.format(i)] == 0, 'quality_{}'.format(i)] = np.nan
for i in [0, 1, 2, 5, 6, 7, 8, 9, 10, 11, 12]:
    test_q_temp.loc[test_q_temp['quality_{}'.format(i)] == 0, 'quality_{}'.format(i)] = np.nan

# 필요없는 변수들을 버려줍니다.
train_q_temp.drop(['time', 'fwver', 'year', 'month', 'day', 'hour', 'minute'], axis=1, inplace=True)
test_q_temp.drop(['time', 'fwver', 'year', 'month', 'day', 'hour', 'minute'], axis=1, inplace=True)

# 그룹바이 카운트 해줍니다.
train_qual_counts = train_q_temp.groupby('user_id').count()
test_qual_counts = test_q_temp.groupby('user_id').count()

# 겹치는 컬럼명을 바꿔줍니다.
train_qual_counts.columns = ['q_c_0', 'q_c_1', 'q_c_2', 'q_c_5', 'q_c_6',
                             'q_c_7', 'q_c_8', 'q_c_9', 'q_c_10', 'q_c_11', 'q_c_12']
test_qual_counts.columns = ['q_c_0', 'q_c_1', 'q_c_2', 'q_c_5', 'q_c_6',
                             'q_c_7', 'q_c_8', 'q_c_9', 'q_c_10', 'q_c_11', 'q_c_12']

# Train & Predict

### Base set

In [493]:
X = train_e.groupby(['user_id', 'errtype'])['errcode'].count().unstack().fillna(0)
y = test_e.groupby(['user_id', 'errtype'])['errcode'].count().unstack().fillna(0)

X.columns = ['et_1', 'et_2', 'et_3', 'et_4', 'et_5', 'et_6', 'et_7', 'et_8', 'et_9', 'et_10', 'et_11', 'et_12', 'et_13',
 'et_14', 'et_15', 'et_16', 'et_17', 'et_18', 'et_19', 'et_20', 'et_21', 'et_22', 'et_23', 'et_24', 'et_25',
 'et_26', 'et_27', 'et_28', 'et_30', 'et_31', 'et_32', 'et_33', 'et_34', 'et_35', 'et_36', 'et_37', 'et_38',
 'et_39', 'et_40', 'et_41', 'et_42']
y.columns = ['et_1', 'et_2', 'et_3', 'et_4', 'et_5', 'et_6', 'et_7', 'et_8', 'et_9', 'et_10', 'et_11', 'et_12', 'et_13',
 'et_14', 'et_15', 'et_16', 'et_17', 'et_18', 'et_19', 'et_20', 'et_21', 'et_22', 'et_23', 'et_24', 'et_25',
 'et_26', 'et_27', 'et_28', 'et_30', 'et_31', 'et_32', 'et_33', 'et_34', 'et_35', 'et_36', 'et_37', 'et_38',
 'et_39', 'et_40', 'et_41', 'et_42']

In [494]:
# 하나 사라진 유저를 채워주는 코드입니다.
y = y.reindex(pd.RangeIndex(y.index.max() + 1)).ffill(0)[30000:]

In [495]:
X.shape, y.shape

((15000, 41), (14999, 41))

### 1차 합병

In [496]:
X = pd.concat([X,
               train_err_count,
               train_fwver_count,
               train_model_count,
               train_qual_std,
               train_qual_log,
               train_errcode_23,
               train_errcode_33,
               train_errcode_34], axis=1).fillna(0)
X.shape

(15000, 73)

In [497]:
y = pd.concat([y,
               test_err_count,
               test_fwver_count,
               test_model_count,
               test_qual_std,
               test_qual_log,
               test_errcode_23,
               test_errcode_33,
               test_errcode_34], axis=1).fillna(0)
y.shape

(14999, 73)

### 2차 합병

In [498]:
X = pd.concat([X, train_qual_counts], axis=1).fillna(0)
y = pd.concat([y, test_qual_counts], axis=1).fillna(0)

X.shape, y.shape

((15000, 84), (14999, 84))

### 2차 면접중

In [499]:
origin_q_train_user = list(train_q.user_id.unique())
train_all_user = list(np.arange(10000, 25000, 1))

In [500]:
origin_q_test_user = list(test_q.user_id.unique())
test_all_user = list(np.arange(30000, 49999, 1))

In [501]:
X_q = X.loc[origin_q_train_user,:]
y_q = y.loc[origin_q_test_user, :]

In [502]:
X_nq = X.drop(origin_q_train_user, axis=0)
y_nq = y.drop(origin_q_test_user, axis=0)

In [506]:
X_q

,et_1,et_2,et_3,et_4,et_5,et_6,et_7,et_8,et_9,et_10,et_11,et_12,et_13,et_14,et_15,et_16,et_17,et_18,et_19,et_20,et_21,et_22,et_23,et_24,et_25,et_26,et_27,et_28,et_30,et_31,et_32,et_33,et_34,et_35,et_36,et_37,et_38,et_39,et_40,et_41,et_42,errcode,fwver,model_nm,q_std_0,q_std_1,q_std_2,q_std_5,q_std_6,q_std_7,q_std_8,q_std_9,q_std_10,q_std_11,q_std_12,time,UNKNOWN,ACTIVE,connLMP,connESTA,connTO,connLOCAL,STANDBY,TERMINATE,err_33_1,err_33_2,err_33_3,err_34_1,err_34_2,err_34_3,err_34_4,err_34_5,err_34_6,q_c_0,q_c_1,q_c_2,q_c_5,q_c_6,q_c_7,q_c_8,q_c_9,q_c_10,q_c_11,q_c_12
user_id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
10000,0.0,0.0,8.0,104.0,0.0,1.0,1.0,0.0,0.0,7.0,15.0,16.0,1.0,10.0,59.0,61.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,32.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,317,1,1,0.000000,0.000000,0.000000,1.793709,0.000000,0.000000,0.0,0.000000,2.043016,0.000000,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,24.0,0.0,0.0
10002,0.0,0.0,2.0,132.0,1.0,2.0,1.0,0.0,0.0,1.0,13.0,14.0,1.0,4.0,52.0,52.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,25.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,306,1,1,0.251312,0.143576,0.177396,1.037404,4.495417,14.547924,0.0,0.332455,2.327185,0.143576,0.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,2.0,3.0,14.0,5.0,24.0,0.0,12.0,84.0,2.0,0.0
10004,0.0,0.0,0.0,1.0,0.0,3.0,4.0,0.0,0.0,0.0,16.0,19.0,3.0,5.0,143.0,91.0,0.0,0.0,0.0,0.0,0.0,140.0,119.0,0.0,0.0,33.0,0.0,0.0,0.0,176.0,0.0,16.0,0.0,0.0,1.0,1.0,0.0,0.0,4.0,0.0,2.0,777,2,1,0.282330,0.282330,0.282330,0.583592,17.778784,44.435591,0.0,0.000000,1.021508,0.282330,0.0,2.0,0.0,7.0,0.0,1.0,104.0,0.0,5.0,2.0,0.0,14.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,2.0,2.0,5.0,3.0,12.0,0.0,0.0,24.0,2.0,0.0
10005,0.0,0.0,0.0,1.0,176.0,0.0,1.0,0.0,0.0,1.0,17.0,17.0,0.0,1.0,109.0,68.0,0.0,0.0,0.0,0.0,0.0,41.0,21.0,2.0,0.0,47.0,1.0,1.0,0.0,114.0,0.0,16.0,1.0,3.0,1.0,1.0,0.0,2.0,44.0,61.0,2.0,749,2,1,0.503610,0.503610,0.503610,1.179536,5.867498,18.387141,0.0,0.000000,1.021508,0.503610,0.0,2.0,0.0,1.0,0.0,0.0,13.0,0.0,3.0,4.0,2.0,12.0,2.0,1.0,0.0,0.0,0.0,0.0,0.0,10.0,10.0,10.0,16.0,12.0,12.0,0.0,0.0,24.0,10.0,0.0
10006,0.0,0.0,0.0,1.0,3.0,2.0,3.0,0.0,0.0,0.0,17.0,17.0,0.0,2.0,114.0,83.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,131.0,0.0,17.0,74.0,1.0,1.0,1.0,0.0,0.0,18.0,0.0,0.0,490,2,2,0.000000,0.000000,0.000000,1.121224,0.666667,1.912366,0.0,0.000000,0.000000,0.000000,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,11.0,4.0,74.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,1.0,12.0,0.0,0.0,36.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24990,65.0,0.0,4.0,161.0,20.0,21.0,9.0,0.0,0.0,0.0,56.0,56.0,0.0,0.0,83.0,36.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,107.0,107.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,725,1,1,0.000000,0.481543,0.481543,0.607919,0.481543,0.000000,0.0,0.000000,0.000000,0.481543,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,24.0,8.0,8.0,10.0,8.0,0.0,0.0,0.0,24.0,8.0,0.0
24992,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,14.0,15.0,0.0,0.0,60.0,14.0,0.0,0.0,0.0,0.0,0.0,27.0,7.0,0.0,0.0,9.0,0.0,0.0,0.0,32.0,0.0,15.0,0.0,0.0,1.0,1.0,0.0,0.0,4.0,2.0,1.0,204,2,1,0.478091,0.478091,0.478091,1.879505,0.478091,0.000000,0.0,0.000000,2.908117,0.478091,0.0,3.0,0.0,0.0,0.0,0.0,4.0,0.0,3.0,0.0,0.0,13.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,12.0,12.0,12.0,16.0,12.0,0.0,0.0,0.0,36.0,12.0,0.0
24993,0.0,0.0,0.0,242.0,6.0,0.0,0.0,0.0,0.0,0.0,14.0,14.0,0.0,0.0,123.0,122.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,32.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,556,1,1,0.464306,0.464306,0.464306,1.334465,0.464306,0.000000,0.0,0.000000,1.021508,0.464306,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0,7.0,7.0,9.0,7.0,0.0,0.0,0.0,24.0,7.0,0.0
24995,0.0,0.0,0.0,0.0,2.0,5.0,5.0,0.0,0.0,0.0,5.0,10.0,8.0,8.0,26.0,18.0,0.0,0.0,0.0,0.0,0.0,17.0,12.0,0.0,0.0,22.0,0.0,0.0,0.0,31.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,7.0,4.0,194,1,1,0.503610,0.503610,0.503610,0.977093,0.503610,0.000000,0.0,0.000000,0.510754,0.503610,0.0,2.0,0.0,4.0,0.0,0.0,0.0,0.0,8.0,0.0,1.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.0,10.0,10.0,12.0,10.0,0.0,0.0,0.0,24.0,10.0,0.0
24997,0.0,0.0,0.0,1.0,8.0,1.0,1.0,0.0,0.0,0.0,16.0,18.0,4.0,1.0,181.0,138.0,0.0,0.0,0.0,0.0,0.0,50.0,29.0,0.0,0.0,49.0,0.0,0.0,0.0,223.0,0.0,16.0,17.0,0.0,1.0,1.0,0.0,0.0,58.0,8.0,5.0,826,2,1,0.380693,0.380693,0.380693,2.060234,0.380693,0.000000,0.0,0.000000,7.661309,0.380693,0.0,2.0,0.0,4.0,0.0,0.0,13.0,1.0,11.0,0.0,3.0,11.0,2.0,2.0,9.0,6.0,0.0,0.0,0.0,4.0,4.0,4.0,10.0,4.0,0.0,0.0,0.0,24.0,4.0,0.0

In [509]:
y_train_q = train_b_p.set_index('user_id').loc[X_q.index, :]
y_train_nq = train_b_p.set_index('user_id').loc[X_nq.index, :]

In [503]:
q_features = ['q_c_0', 'q_c_1', 'q_c_2', 'q_c_5', 'q_c_6', 'q_c_7', 'q_c_8',
              'q_c_9', 'q_c_10', 'q_c_11', 'q_c_12', 'q_std_0', 'q_std_1',
              'q_std_2', 'q_std_5', 'q_std_6', 'q_std_7','q_std_8', 'q_std_9',
              'q_std_10','q_std_11', 'q_std_12']

X_nq.drop(q_features, axis=1, inplace=True)
y_nq.drop(q_features, axis=1, inplace=True)

In [377]:
# X_temp = pd.concat([X, train_qual_mean], axis=1).fillna(0)
# y_temp = pd.concat([y, test_qual_mean], axis=1).fillna(0)

# X_temp.shape, y_temp.shape

((15000, 95), (14999, 95))

In [379]:
# X_del = X.drop(['et_8', 'et_9'], axis=1)
# y_del = y.drop(['et_8', 'et_9'], axis=1)

## Model

In [193]:
#------------------------------------------------------------
# validation auc score를 확인하기 위해 정의
def f_pr_auc(probas_pred, y_true):
    labels=y_true.get_label()
    p, r, _ = precision_recall_curve(labels, probas_pred)
    score=auc(r,p) 
    return "pr_auc", score, True
#------------------------------------------------------------


def s_fold_train_pred(train_x, train_y):
    import lightgbm as lgb

    # Train
    models     = []
    recalls    = []
    precisions = []
    auc_scores   = []
    threshold = 0.5
    # 파라미터 설정
    params =      {
                    'boosting_type' : 'gbdt',
                    'objective'     : 'binary',
                    'metric'        : 'auc',
                    'learning_rate' : 0.027,
                    'seed': 42
                    }
    #-------------------------------------------------------------------------------------
    # 5 Kfold cross validation
    s_fold = StratifiedKFold(n_splits=5, shuffle=True ,random_state=42)    

    for train_idx, val_idx in s_fold.split(train_x, train_y):

        # split train, validation set
        X = train_x.iloc[train_idx]
        y = train_y.iloc[train_idx]
        valid_x = train_x.iloc[val_idx]
        valid_y = train_y.iloc[val_idx]

        d_train= lgb.Dataset(X, y)
        d_val  = lgb.Dataset(valid_x, valid_y)

        #run traning
        model = lgb.train(
                            params,
                            train_set       = d_train,
                            num_boost_round = 10000,
                            valid_sets      = d_val,
                            feval           = f_pr_auc,
                            verbose_eval    = 100, 
                            early_stopping_rounds = 100
                           )

        # cal valid prediction
        valid_prob = model.predict(valid_x)
        valid_pred = np.where(valid_prob > threshold, 1, 0)

        # cal scores
        recall    = recall_score(    valid_y, valid_pred)
        precision = precision_score( valid_y, valid_pred)
        auc_score = roc_auc_score(   valid_y, valid_prob)

        # append scores
        models.append(model)
        recalls.append(recall)
        precisions.append(precision)
        auc_scores.append(auc_score)

        print('==========================================================')
        
    return models, auc_scores, recalls, precisions

In [194]:
# loss 비교를 위해 지우지 않습니다.
# 최고점 모델입니다.
models, auc_scores, _, _ = s_fold_train_pred(X, train_b_p.target)
print(np.mean(auc_scores))

[LightGBM] [Info] Number of positive: 4000, number of negative: 8000
[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 0.003685 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 9975
[LightGBM] [Info] Number of data points in the train set: 12000, number of used features: 84
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.333333 -> initscore=-0.693147
[LightGBM] [Info] Start training from score -0.693147
Training until validation scores don't improve for 100 rounds
[100]	valid_0's auc: 0.825269	valid_0's pr_auc: 0.740748
[200]	valid_0's auc: 0.826495	valid_0's pr_auc: 0.749447
Early stopping, best iteration is:
[190]	valid_0's auc: 0.826685	valid_0's pr_auc: 0.750194
==========================================================
[LightGBM] [Info] Number of positive: 4000, number of negative: 8000
[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 0.003654 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 10062
[LightGBM] [Info] Number of data points in the train set: 12000, number of used features: 84
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.333333 -> initscore=-0.693147
[LightGBM] [Info] Start training from score -0.693147
Training until validation scores don't improve for 100 rounds
[100]	valid_0's auc: 0.83427	valid_0's pr_auc: 0.775623
[200]	valid_0's auc: 0.835291	valid_0's pr_auc: 0.778994
Early stopping, best iteration is:
[169]	valid_0's auc: 0.835614	valid_0's pr_auc: 0.777808
==========================================================
[LightGBM] [Info] Number of positive: 4000, number of negative: 8000
[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 0.003375 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 10071
[LightGBM] [Info] Number of data points in the train set: 12000, number of used features: 84
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.333333 -> initscore=-0.693147
[LightGBM] [Info] Start training from score -0.693147
Training until validation scores don't improve for 100 rounds
[100]	valid_0's auc: 0.822679	valid_0's pr_auc: 0.747001
[200]	valid_0's auc: 0.82816	valid_0's pr_auc: 0.753692
[300]	valid_0's auc: 0.828545	valid_0's pr_auc: 0.753229
Early stopping, best iteration is:
[236]	valid_0's auc: 0.828966	valid_0's pr_auc: 0.753945
==========================================================
[LightGBM] [Info] Number of positive: 4000, number of negative: 8000
[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 0.003553 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 10072
[LightGBM] [Info] Number of data points in the train set: 12000, number of used features: 84
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.333333 -> initscore=-0.693147
[LightGBM] [Info] Start training from score -0.693147
Training until validation scores don't improve for 100 rounds
[100]	valid_0's auc: 0.830018	valid_0's pr_auc: 0.752228
[200]	valid_0's auc: 0.830946	valid_0's pr_auc: 0.75797
Early stopping, best iteration is:
[161]	valid_0's auc: 0.831498	valid_0's pr_auc: 0.757458
==========================================================
[LightGBM] [Info] Number of positive: 4000, number of negative: 8000
[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 0.004379 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 10067
[LightGBM] [Info] Number of data points in the train set: 12000, number of used features: 84
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.333333 -> initscore=-0.693147
[LightGBM] [Info] Start training from score -0.693147
Training until validation scores don't improve for 100 rounds
[100]	valid_0's auc: 0.818095	valid_0's pr_auc: 0.726772
[200]	valid_0's auc: 0.819226	valid_0's pr_auc: 0.736312
Early stopping, best iteration is:
[180]	valid_0's auc: 0.819375	valid_0's pr_auc: 0.735405
==========================================================
0.8284274999999999

In [510]:
# 학습용
models, auc_scores, _, _ = s_fold_train_pred(X_q, y_train_q)
print(np.mean(auc_scores))

[LightGBM] [Info] Number of positive: 2533, number of negative: 4091
[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 0.002696 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 9579
[LightGBM] [Info] Number of data points in the train set: 6624, number of used features: 84
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.382397 -> initscore=-0.479385
[LightGBM] [Info] Start training from score -0.479385
Training until validation scores don't improve for 100 rounds
[100]	valid_0's auc: 0.788708	valid_0's pr_auc: 0.718566
[200]	valid_0's auc: 0.790819	valid_0's pr_auc: 0.720356
[300]	valid_0's auc: 0.792358	valid_0's pr_auc: 0.727782
[400]	valid_0's auc: 0.791522	valid_0's pr_auc: 0.728766
Early stopping, best iteration is:
[350]	valid_0's auc: 0.7926	valid_0's pr_auc: 0.728565
==========================================================
[LightGBM] [Info] Number of positive: 2534, number of negative: 4091
[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 0.002896 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 9534
[LightGBM] [Info] Number of data points in the train set: 6625, number of used features: 84
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.382491 -> initscore=-0.478990
[LightGBM] [Info] Start training from score -0.478990
Training until validation scores don't improve for 100 rounds
[100]	valid_0's auc: 0.800626	valid_0's pr_auc: 0.754664
[200]	valid_0's auc: 0.800597	valid_0's pr_auc: 0.754381
Early stopping, best iteration is:
[138]	valid_0's auc: 0.80254	valid_0's pr_auc: 0.756615
==========================================================
[LightGBM] [Info] Number of positive: 2534, number of negative: 4091
[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 0.003219 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 9605
[LightGBM] [Info] Number of data points in the train set: 6625, number of used features: 84
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.382491 -> initscore=-0.478990
[LightGBM] [Info] Start training from score -0.478990
Training until validation scores don't improve for 100 rounds
[100]	valid_0's auc: 0.811421	valid_0's pr_auc: 0.753802
[200]	valid_0's auc: 0.810666	valid_0's pr_auc: 0.764519
Early stopping, best iteration is:
[119]	valid_0's auc: 0.813327	valid_0's pr_auc: 0.76122
==========================================================
[LightGBM] [Info] Number of positive: 2534, number of negative: 4091
[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 0.002980 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 9585
[LightGBM] [Info] Number of data points in the train set: 6625, number of used features: 84
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.382491 -> initscore=-0.478990
[LightGBM] [Info] Start training from score -0.478990
Training until validation scores don't improve for 100 rounds
[100]	valid_0's auc: 0.812644	valid_0's pr_auc: 0.751062
Early stopping, best iteration is:
[46]	valid_0's auc: 0.808945	valid_0's pr_auc: 0.766608
==========================================================
[LightGBM] [Info] Number of positive: 2533, number of negative: 4092
[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 0.002812 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 9580
[LightGBM] [Info] Number of data points in the train set: 6625, number of used features: 84
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.382340 -> initscore=-0.479629
[LightGBM] [Info] Start training from score -0.479629
Training until validation scores don't improve for 100 rounds
[100]	valid_0's auc: 0.806799	valid_0's pr_auc: 0.775439
[200]	valid_0's auc: 0.807356	valid_0's pr_auc: 0.781204
Early stopping, best iteration is:
[130]	valid_0's auc: 0.80938	valid_0's pr_auc: 0.781139
==========================================================
0.805358375566829

In [525]:
# 학습용
models_2, auc_scores, _, _ = s_fold_train_pred(X_nq, y_train_nq)
print(np.mean(auc_scores))

[LightGBM] [Info] Number of positive: 1466, number of negative: 3909
[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 0.001687 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 4377
[LightGBM] [Info] Number of data points in the train set: 5375, number of used features: 60
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.272744 -> initscore=-0.980744
[LightGBM] [Info] Start training from score -0.980744
Training until validation scores don't improve for 100 rounds
[100]	valid_0's auc: 0.840908	valid_0's pr_auc: 0.719896
[200]	valid_0's auc: 0.842614	valid_0's pr_auc: 0.712149
Early stopping, best iteration is:
[112]	valid_0's auc: 0.841159	valid_0's pr_auc: 0.721601
==========================================================
[LightGBM] [Info] Number of positive: 1466, number of negative: 3909
[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 0.001675 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 4377
[LightGBM] [Info] Number of data points in the train set: 5375, number of used features: 60
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.272744 -> initscore=-0.980744
[LightGBM] [Info] Start training from score -0.980744
Training until validation scores don't improve for 100 rounds
[100]	valid_0's auc: 0.842046	valid_0's pr_auc: 0.744345
Early stopping, best iteration is:
[53]	valid_0's auc: 0.840056	valid_0's pr_auc: 0.745844
==========================================================
[LightGBM] [Info] Number of positive: 1466, number of negative: 3909
[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 0.001683 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 4343
[LightGBM] [Info] Number of data points in the train set: 5375, number of used features: 61
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.272744 -> initscore=-0.980744
[LightGBM] [Info] Start training from score -0.980744
Training until validation scores don't improve for 100 rounds
[100]	valid_0's auc: 0.821347	valid_0's pr_auc: 0.706368
[200]	valid_0's auc: 0.820408	valid_0's pr_auc: 0.716271
Early stopping, best iteration is:
[140]	valid_0's auc: 0.822212	valid_0's pr_auc: 0.714128
==========================================================
[LightGBM] [Info] Number of positive: 1467, number of negative: 3908
[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 0.001691 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 4397
[LightGBM] [Info] Number of data points in the train set: 5375, number of used features: 61
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.272930 -> initscore=-0.979806
[LightGBM] [Info] Start training from score -0.979806
Training until validation scores don't improve for 100 rounds
[100]	valid_0's auc: 0.810925	valid_0's pr_auc: 0.680515
[200]	valid_0's auc: 0.80919	valid_0's pr_auc: 0.684371
Early stopping, best iteration is:
[116]	valid_0's auc: 0.812591	valid_0's pr_auc: 0.688597
==========================================================
[LightGBM] [Info] Number of positive: 1467, number of negative: 3909
[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 0.001679 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 4404
[LightGBM] [Info] Number of data points in the train set: 5376, number of used features: 60
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.272879 -> initscore=-0.980062
[LightGBM] [Info] Start training from score -0.980062
Training until validation scores don't improve for 100 rounds
[100]	valid_0's auc: 0.828774	valid_0's pr_auc: 0.737077
[200]	valid_0's auc: 0.83139	valid_0's pr_auc: 0.741349
[300]	valid_0's auc: 0.833503	valid_0's pr_auc: 0.743487
[400]	valid_0's auc: 0.835396	valid_0's pr_auc: 0.744119
Early stopping, best iteration is:
[368]	valid_0's auc: 0.835799	valid_0's pr_auc: 0.744117
==========================================================
0.8303632420546047

In [526]:
pred_y_list = []
for model in models:
    pred_y = model.predict(y_q)
    pred_y_list.append(pred_y.reshape(-1,1))
    
pred_ensemble = np.mean(pred_y_list, axis = 0)

In [527]:
pred_y_list = []
for model in models_2:
    pred_y = model.predict(y_nq)
    pred_y_list.append(pred_y.reshape(-1,1))
    
pred_ensemble_2 = np.mean(pred_y_list, axis = 0)

In [512]:
submission.problem = pred_ensemble
submission

ValueError: Length of values does not match length of index

In [382]:
#submission.to_csv(r'C:\Users\Wyatt\wyatt37/Comp/LG_edge_detect/king/submission/king_210123_1_del8th9th.csv', index=False)

# Evaluation

### 1,2차 합본

0.8075 -> 0.8161로 상승했습니다. 그래도 0.9% 오른거면 꽤나 올랐네요!

### 1,2차 합본 파라미터 튜닝

파라미터 튜닝을 해줬는데, 0.8161 -> 0.8222	로 상승했습니다. lgbm 만세! 0.6% 올랐습니다.

바꾼 파라미터

1. lr {'default' : 0.027}
2. num_boost_round {1000:10000}
3. early_stopping_rounds {3 :100}

미세하게 많이 개선하도록 바꿨습니다.

### 3차 합본

specific error count 를 넣으니 성능이 오히려 떨어졌습니다.

0.8217로 큰 차이는 없으나 Loss를 따라가는 것 같습니다.

하나씩 줄여가면서 다시 학습을 시켜보겠습니다.

하나씩 학습시켜보았으나, 기존의 로스를 넘는 변수는 없었음

### 4차 합본

0.8222 -> 0.8228 로 아주 미세하게 상승 0.0006 상승했습니다.

### 5차 합본

1. 'conn' 이 포함된 errcode의 갯수: 기각
2. robot 형식의 errcode의 갯수: 기각
3. 'android'가 들어간 errcode의 갯수: 기각

안드로이드는 0.8228 -> 0.8230 으로 아주 미세하게 0.0002 상승했습니다. 그러나 기각시켰습니다. 이유는 fc1에 있습니다.

### 오버샘플링

1. Over Sampling by SMOTE-B: 이상한 로스가 나오면서 리더보드 떨어짐

### 6차 합본

1. 23호, 33호, 34호가 살아남았습니다.

### 7차 합본

1. quality count: 각 퀄리티별 0이 아닌 로그 개수 ->>> 로스는 떨어졌으나, 리더보드 아주 미세하게 오름.
2. quality time gap: 유저별 퀄리티 로그의 발생 간격의 합 ->>> 로스도, 리더보드도 아주 미세하게 떨어짐.
3. quality time continue: 유저별 퀄리티 로그의 연속 발생 횟수(2시간 뒤에 바로 2시간이 기록되면 1을 더해줌) ->>> 로스도, 리더보드도 아주 미세하게 떨어짐
4. quality onehot: 0을 제외한 값을 전부 1로 바꿔서 groupby().max() 값으로 뽑았음 ->>> 로스가 너무 떨어져서 제출 기각
5. quality mean: 음...std랑 함께 넣으면 더 나아질까 싶어 넣어봤습니다.->>> 로스는 올랐으나, 리더보드는 미세하게 떨어짐.

### 변수 제거

1. 8호와 9호를 제거해보았습니다. 리더보드 떨어졌습니다.